### ISSUE TITLE
Unable to resolve activity for Intent

### ISSUE THREAD

**Issue by sedubois** [takahirom/roborazzi#100]
Thank you for building this library. I tried to generate a screenshot in my existing Android app project using Robolectric 4.10.3 by adding the following:

```toml
# libs.versions.toml
roborazzi = "1.3.0-alpha-4"
roborazzi-core = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }
roborazzi-compose = { group = "io.github.takahirom.roborazzi", name = "roborazzi-compose", version.ref = "roborazzi" }
roborazzi-junitRule = { group = "io.github.takahirom.roborazzi", name = "roborazzi-junit-rule", version.ref = "roborazzi" }
[plugins]
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
```

```kotlin
// build.gradle.kts
plugins {
    // ...
    alias(libs.plugins.roborazzi) apply false
}
```
```kotlin
// app/build.gradle.kts
plugins {
    // ...
    alias(libs.plugins.roborazzi)
}
dependencies {
    // ...
    testImplementation(libs.roborazzi.core)
    testImplementation(libs.roborazzi.compose)
    testImplementation(libs.roborazzi.junitRule)
}
```

```kotlin
// test/kotlin/com/myapp/RoborazziTest.kt
package com.myapp

import androidx.compose.material3.Text
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.github.takahirom.roborazzi.captureRoboImage
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.annotation.GraphicsMode
import org.robolectric.annotation.GraphicsMode.Mode.NATIVE

@RunWith(AndroidJUnit4::class)
@GraphicsMode(NATIVE)
class RoborazziTest {
    @Test
    fun roborazziTest() {
        captureRoboImage {
            Text("Hello Compose!")
        }
    }
}
```

I then ran the test (along with all other tests the app already has - how to run only this one and still record the screenshot from Android Studio?) as follows:
```
./gradlew recordRoborazziDebug
```

But I then encounter the following error:

```
java.lang.RuntimeException: Unable to resolve activity for Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.myapp.debug/com.github.takahirom.roborazzi.RoborazziTransparentActivity } -- see https://github.com/robolectric/robolectric/pull/4736 for details
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.startActivitySyncInternal(RoboMonitoringInstrumentation.java:98)
	at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:35)
	at org.robolectric.android.internal.LocalActivityInvoker.startActivity(LocalActivityInvoker.java:40)
	at androidx.test.core.app.ActivityScenario.launchInternal(ActivityScenario.java:362)
	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:202)
	at com.github.takahirom.roborazzi.RoborazziComposeKt.captureRoboImage(RoborazziCompose.kt:29)
	at com.github.takahirom.roborazzi.RoborazziComposeKt.captureRoboImage(RoborazziCompose.kt:16)
	at com.github.takahirom.roborazzi.RoborazziComposeKt.captureRoboImage$default(RoborazziCompose.kt:11)
	at com.myapp.RoborazziTest.roborazziTest(RoborazziTest.kt:16)
```

However, I don't know what to make with the [provided Robolectric PR link](https://github.com/robolectric/robolectric/pull/4736). What should I concretely do to make the task succeed and generate the screenshot? Currently there is no folder `build/outputs/roborazzi` generated.

**Comment by takahirom** [comment]
Could you check if you use includeAndroidResources = true to use activity?

android {
  testOptions {
    unitTests {
      includeAndroidResources = true
    }
  }
}

It is in the getting started of Robolectric.
https://robolectric.org/getting-started/

**Comment by sedubois** [comment]
Yes, build.gradle.kts contains this (the app already has Robolectric tests):

```kts
android {
    // ...
    testOptions.unitTests.isIncludeAndroidResources = true
}
```

**Comment by takahirom** [comment]
It may be because you are using Activity in the application module. Could you try the solution provided here? https://github.com/robolectric/robolectric/pull/4736#issuecomment-1358130974

**Comment by takahirom** [comment]
It will be something like this 👀 

```kotlin
        val appContext: Application = ApplicationProvider.getApplicationContext()
        val activityInfo = ActivityInfo().apply {
            name = "com.github.takahirom.roborazzi.RoborazziTransparentActivity"
            packageName = appContext.packageName
        }
        shadowOf(appContext.packageManager).addOrUpdateActivity(activityInfo)
```

**Comment by takahirom** [comment]
We could make adjustments on the library side to utilize the export Activity in our library. I'm not sure if it would work though 👀 
https://github.com/robolectric/robolectric/pull/4736#issuecomment-1117112155

**Comment by takahirom** [comment]
I tried `export=true` but it seems that we need to use addOrUpdateActivity 🤔 
https://github.com/takahirom/roborazzi/compare/takahirom/application-module/2023-06-18?expand=1

**Comment by sedubois** [comment]
Thanks for the tips @takahirom, where should I put that code exactly, and what is the `TestActivity`? I have no such class in my codebase. 

Here's how one of my Robolectric tests looks like (the app has a single `MainActivity`):

```kotlin
@RunWith(AndroidJUnit4::class)
class MyTest {
    @get:Rule val composeRule = createAndroidComposeRule(MainActivity::class.java)

    @Test
    fun myTest() {
        composeRule.apply {
            activity.setContent {
                MyComposable()
            }
            // onNode(...) assertions go here
        }
    }
}
```

**Comment by takahirom** [comment]
As far as I know, testing Jetpack Compose with Robolectric has certain limitations.

1. Jetpack Compose tests require an Activity.
2. The Activity must be registered in the AndroidManifest.

The reason we have a TestActivity is due to the first point. If we use it, we can narrow down the scope of the tests. Using MainActivity is also a good option, with the difference being merely the scope.
The 'Unable to resolve activity' issue arises because of the second point. I'm not entirely sure why, but if you use the com.android.application plugin, it seems that the Activities listed in test/Manifest.xml are not visible. Hence, we need to register it separately.
My suggestion is that you might not need to use setContent, as MainActivity should handle that.
For further clarification, you can refer to the documentation of createAndroidComposeRule.

**Comment by takahirom** [comment]
I believe this isn't related to Roborazzi, so I'll proceed with closing it. I will respond to your questions, and if any other problem arises, I'll reopen this issue.

**Comment by sedubois** [comment]
Thank you @takahirom, I had missed the `com.github.takahirom.roborazzi.RoborazziTransparentActivity` in your previous message. With the test below, the screenshot gets generated as expected when running `./gradlew recordRoborazziDebug`.

I'm not sure why the issue is closed, because as it stands, the README documentation of this library doesn't allow to record screenshots for Robolectric tests. It was necessary to apply the TestRule defined below. Isn't that something this library should take care of automatically?

Also, why don't the screenshots get recorded when running the tests (individually or collectively) from Android Studio? That is another thing that looks like a bug at first glance. I would expect the screenshot to be generated when calling `captureRoboImage`.

```kotlin
package com.myapp

import android.app.Application
import android.content.pm.ActivityInfo
import androidx.test.core.app.ApplicationProvider
import org.junit.rules.TestRule
import org.junit.runner.Description
import org.junit.runners.model.Statement
import org.robolectric.Shadows

class RoborazziRule : TestRule {
    override fun apply(base: Statement, description: Description) = object : Statement() {
        override fun evaluate() {
            val appContext: Application = ApplicationProvider.getApplicationContext()
            val activityInfo = ActivityInfo().apply {
                name = "com.github.takahirom.roborazzi.RoborazziTransparentActivity"
                packageName = appContext.packageName
            }
            Shadows.shadowOf(appContext.packageManager).addOrUpdateActivity(activityInfo)
            base.evaluate()
        }
    }
}
```

```kotlin
package com.myapp

import androidx.compose.material3.Text
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.github.takahirom.roborazzi.captureRoboImage
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.annotation.GraphicsMode
import org.robolectric.annotation.GraphicsMode.Mode.NATIVE

@RunWith(AndroidJUnit4::class)
@GraphicsMode(NATIVE)
class RoborazziTest {
    @get:Rule val roborazziRule = RoborazziRule()

    @Test
    fun roborazziTest() {
        captureRoboImage {
            Text("Hello world!")
        }
    }
}
```

**Comment by takahirom** [comment]
Thank you for your suggestion. I have several reasons for not pursuing it.

* It would create an explicit dependency on Robolectric, which could limit the library's versatility.
* The Robolectric rule isn't necessary when using captureRoboImage(). Therefore, we can't depend solely on the Rule.
* I'm uncertain about the performance impact of addActivityIfNotPresent. This is because we don't need to use it when working with the library module.
* The workaround can be found in the URL provided when you view the issue.

However, I do want to address this issue and there might be potential workarounds. Hence, I've decided to reopen this issue.

**Comment by sedubois** [comment]
> The Robolectric rule isn't necessary when using captureRoboImage()

@takahirom as shown [above](https://github.com/takahirom/roborazzi/issues/100#issuecomment-1596108318), the rule was necessary for the screenshot to get recorded when using `captureRoboImage { Text("Hello world!") }`.

**Comment by takahirom** [comment]
It seems it doesn't take a lot of time to execute. So I'm going to add it to `captureRoboImage{}`

> register:1

```kotlin
  println("register:" + measureTimeMillis {
    registerRoborazziActivityToRobolectric()
  })


private fun registerRoborazziActivityToRobolectric() {
  try {
    val appContext: Application = ApplicationProvider.getApplicationContext()
    Shadows.shadowOf(appContext.packageManager).addActivityIfNotPresent(
      ComponentName(
        appContext.packageName,
        RoborazziTransparentActivity::class.java.name,
      )
    )
  } catch (e: ClassNotFoundException) {
    // We don't rely on Robolectric
    e.printStackTrace()
  }
}
```


* It would create an explicit dependency on Robolectric, which could limit the library's versatility.
→ We can reduce it by catching `ClassNotFoundException`

* The Roborazzi rule isn't necessary when using captureRoboImage(). Therefore, we can't depend solely on the Rule.
→ We can do it in  `captureRoboImage{}`

I'm uncertain about the performance impact of addActivityIfNotPresent. This is because we don't need to use it when working with the library module.
→ It doesn't take a lot of time.
