### ISSUE TITLE
Single compose test always fails locally, does not fail CI verify call even when snapshots are missing

### ISSUE THREAD

**Issue by ZacSweers** [takahirom/roborazzi#104]
Repro: https://github.com/slackhq/circuit/pull/669

Run the `PetListSnapshotTest.petList_show_list_for_success_state()` test, observe that it always fails locally and cannot record a new snapshot. On CI however, the verify calls always pass despite there being no available snapshot.

This is using 1.3.0-alpha-4

**Comment by takahirom** [comment]
Thank you. I believe the issue lies with RoborazziRule. Could you please remove it? It's set to take screenshots automatically, which is causing the test to fail. The RoborazziRule seems rather confusing to me. We'll need to modify the API sooner or later.

**Comment by takahirom** [comment]
Another issue is that the tests are being skipped. I suspect this might be happening due to existing cache. What do you think?

**Comment by takahirom** [comment]
@ZacSweers 
I've refactored the RoborazziRule to provide a default file path and to fix the CaptureType.LastImage behavior. This update will be included in the 1.4.0-alpha-1 version. Could you please take a look at it?
https://github.com/takahirom/roborazzi/pull/105

**Comment by takahirom** [comment]
I believe it is better than the current implementation. Let me merge

**Comment by ZacSweers** [comment]
Cool, I can try that version when it's out

**Comment by ZacSweers** [comment]
looks like that's working 👍
