### ISSUE TITLE
Incomplete display of generated images

### ISSUE THREAD

**Issue by qdsfdhvh** [takahirom/roborazzi#114]
Hi, thanks for build this library. I did the [configuration](https://github.com/qdsfdhvh/compose-imageloader/pull/201/files) as same as example.

```kotlin
@RunWith(AndroidJUnit4::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
class ComposeScreenShotTest {

    @get:Rule
    val composeTestRule = createAndroidComposeRule<ComponentActivity>()

    @get:Rule
    val roborazziRule = RoborazziRule(
        composeRule = composeTestRule,
        captureRoot = composeTestRule.onRoot(),
        options = RoborazziRule.Options(
            outputDirectoryPath = "src/androidUnitTest/snapshots/images",
        ),
    )

    @Test
    fun loadImage() {
        composeTestRule.setContent {
            Spacer(
                Modifier.size(100.dp).background(Color.Red),
            )
        }
    }
}
```

But when I run `./gradlew recordRoborazziDebug`, generated images is like this:

![com seiko imageloader screenshot ComposeScreenShotTest loadImage](https://github.com/takahirom/roborazzi/assets/17807925/4572d952-a1e6-4f04-934f-ac898cc291ae)

## My environment:

- Gradle: 8.2
- AGP: 8.0.2
- Kotlin: 1.8.20
- Compose-MultiPlatform: 1.4.1
- Roborazzi: 1.4.0-alpha-2
- Robolectric: 4.10.3

**Comment by takahirom** [comment]
Thanks, I'll check it out 👀

**Comment by takahirom** [comment]
It seems Robolectric isn't functioning properly because the fundamental drawToBitmap() operation is not working. However, RobolectricTestRunner appears to be working, so I'm unsure where the issue lies 😭
This may be related to KMP or Compose Multiplatform, but I can't ascertain the cause.

I'm using the same code for your project and my project.

```kotlin
@RunWith(AndroidJUnit4::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
class ComposeScreenShotTest {

    @get:Rule
    val composeTestRule = createAndroidComposeRule<ComponentActivity>()
    @get:Rule
    val roborazziRule = RoborazziRule(
        captureRoot = onView(isRoot()),
        options = RoborazziRule.Options(
            roborazziOptions = RoborazziOptions(
                captureType = CaptureType.Screenshot()
            ),
            outputDirectoryPath = "src/androidUnitTest/snapshots/images",
        ),
    )

    @Test
    fun loadImage() {
        composeTestRule.setContent {
            Box(
                Modifier
                    .size(100.dp)
                    .testTag("box")
                    .background(Color.Red),
            ) {
                Box(
                    Modifier
                        .size(50.dp)
                        .testTag("box2")
                        .background(Color.Blue),
                )
            }
        }
    }
}
```

Roborazzi sample result
<img width="643" alt="image" src="https://github.com/takahirom/roborazzi/assets/1386930/1a272faa-ae0b-4ffc-9e17-65e9adec5d47">

Your project result (compose-imageloader)
<img width="657" alt="image" src="https://github.com/takahirom/roborazzi/assets/1386930/ce532254-a021-415e-b6e8-dd92f60a97de">

**Comment by takahirom** [comment]
I'm going to investigate the difference between your project and my project.

**Comment by takahirom** [comment]
I found the problem!
I'm going to take a look more but you can fix it by adding `@Config(sdk = [32])` to your test? This should fix your issue

**Comment by takahirom** [comment]
api = 25 doesn't work
<img width="288" alt="image" src="https://github.com/takahirom/roborazzi/assets/1386930/57e78605-feb7-45c2-aa3d-23553d617874">
api = 26 work
<img width="247" alt="image" src="https://github.com/takahirom/roborazzi/assets/1386930/7bcd144c-41de-4703-9862-f399e6ebbc08">

**Comment by takahirom** [comment]
I'm going to implement a warning to avoid the capture below API Level 25.
Thanks for reporting this!

**Comment by qdsfdhvh** [comment]
It works! Thanks for your help.

**Comment by LloydBlv** [comment]
This is still happening on recent version and adding the @Config fixed it , maybe something to include in the home README.md file?

**Comment by takahirom** [comment]
@LloydBlv Thank you for your feedback. There was a warning for it, but it seems it was not sufficient. I have included it in the FAQ.
https://github.com/takahirom/roborazzi?tab=readme-ov-file#q-the-images-taken-from-roborazzi-seem-broken
