### ISSUE TITLE
Support to run Roborazzi tests from Android Studio

### ISSUE THREAD

**Issue by sergio-sastre** [takahirom/roborazzi#117]
Currently, one can run Roborazzi tests only by  running a couple of custom tasks, which are mainly a copy paste from Paparazzi.

I believe this is not necessary and would be awesome to be able to additionally run tests directly from Android Studio.

The idea is to do sth similar to Dropshots:
- the verification of the screenshots happens inside the test itself, and not after all screenshots are recorded. Not sure if that’s how it is currently done.
- Instead of having a custom task to run tests (:recordRoborazziTest/:verifyRoborazziTest) one would reuse the already existing task for that (:testDebugUnitTest), and use a gradle property to decide whether to record or verify the test e.g roborazzi.record

Dropshots does that with :connectedAndroidTest, that is the analogue task for instrumentation tests, and that allows to run the screenshot tests directly from Android studio

**Comment by takahirom** [comment]
Thanks as always.
The documentation doesn't cover this, but you can run it with -Proborazzi.test.record=true, which can be set in Android Studio. I sometimes debug using this method. Do you have any recommendations for more efficient ways or other methods?

**Comment by takahirom** [comment]
Something like this? 👀 

```kotlin
roborazzi {
  unitTestDefaultBehavior "record"
}
```

**Comment by sergio-sastre** [comment]
> Thanks as always.
> The documentation doesn't cover this, but you can run it with -Proborazzi.test.record=true, which can be set in Android Studio. I sometimes debug using this method. Do you have any recommendations for more efficient ways or other methods?

> Thanks as always.
> The documentation doesn't cover this, but you can run it with -Proborazzi.test.record=true, which can be set in Android Studio. I sometimes debug using this method. Do you have any recommendations for more efficient ways or other methods?

Wow! That is exactly what I meant.
Definitely sth I’d add to the documentation, since I didn’t know that it was possible.
I’ll try it and close the issue if works as expected 😊

**Comment by sergio-sastre** [comment]
> Something like this? 👀
> 
> ```kotlin
> roborazzi {
>   unitTestDefaultBehavior "record" // none may be default
> }
> ```

For me, that with the property is enough as far as it is documented.
I’m afraid that enabling one more way to do it might lead to misunderstandings if one sets the property in gradle and also a variable in the roborazzi task that contradicts the property

**Comment by takahirom** [comment]
I forgot to mention that we have some tasks to tackle before we can effectively highlight the parameters in the README.

1. At the moment, the system property (-Proborazzi.record=true) takes precedence over the task (recordRoborazziDebug). This can be counterintuitive.
Maybe we should reorder the code here.

https://github.com/takahirom/roborazzi/blob/main/include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt#L107C28-L107C28

And add the test
https://github.com/takahirom/roborazzi/blob/main/include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProjectTest.kt

2. We have separated the comparison task to summarize the report. It should be designated as doLast in the test, primarily because the task doesn't execute with the system property. 

https://github.com/takahirom/roborazzi/blob/main/include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt#L158-L179

**Comment by sergio-sastre** [comment]
I believe with System property you meant -D instead of -P?

Because adding the gradle property in `gradle.properties` does not take effect,
`roborazzi.record=true`

I believe that is because unit tests use system properties, and they have to be propagated to Gradle, e.g.
```groovy
unitTests.all {
   systemProperty 'roborazzi.record', 'true' // this is the default
}
```

Moreover, with or without the gradle property, I could not get the tests running from Android studio if they are parameterized, but I doubt it has to do with roborazzi:
[parameterized roborazzi test](https://github.com/sergio-sastre/Android-screenshot-testing-playground/blob/master/lazycolumnscreen/roborazzi/src/test/java/com/example/road/to/effective/snapshot/testing/lazycolumnscreen/roborazzi/compose/parameterized/CoffeeDrinkListComposableWithParameterizedRunnerTest.kt)

Note: I'm using Roborazzi 1.2.0 though.

**Comment by takahirom** [comment]
Well, we have an integration test for `-P` parameter. And it works.

```kotlin
fun recordWithSystemParameter(): BuildResult {
    val task = "testDebugUnitTest"
    return runTask(task, additionalParameters = arrayOf("-Proborazzi.test.record=true"))
  }
```

```kotlin
    RoborazziGradleProject(testProjectDir).apply {
      unitTest()
      // Record task shouldn't be skipped even after unit test
      recordWithSystemParameter()

      checkCompareFileNotExists()
      checkRecordedFileExists("$screenshotAndName.testCapture.png")
      checkRecordedFileNotExists("$screenshotAndName.testCapture_compare.png")
      checkRecordedFileNotExists("$screenshotAndName.testCapture_actual.png")
    }
```

And I use it as a parameter as debug. (I did it for debugging https://github.com/takahirom/roborazzi/issues/114 problem)

<img width="627" alt="image" src="https://github.com/takahirom/roborazzi/assets/1386930/49f30371-d017-45dc-8ec4-055cca73e9a3">


And I often use it in `gradle.properties` in my personal project.

```
# roborazzi
roborazzi.test.record=true
roborazzi.record.resizeScale=0.5
roborazzi.record.namingStrategy=testClassAndMethod
```

**Comment by takahirom** [comment]
Maybe you should use `roborazzi.test.record ` instead of `roborazzi.record `?

**Comment by takahirom** [comment]
I think Roborazzi is ready to have documentation written about its properties. ✍️
https://github.com/takahirom/roborazzi/issues/117#issuecomment-1629907657

**Comment by sergio-sastre** [comment]
> Maybe you should use `roborazzi.test.record ` instead of `roborazzi.record `?

Good catch! Let me try it later this evening (CET Berlin) & I'll give you feedback

**Comment by sergio-sastre** [comment]
> > Maybe you should use `roborazzi.test.record ` instead of `roborazzi.record `?
> 
> Good catch! Let me try it later this evening (CET Berlin) & I'll give you feedback

So I can confirm it works but not as I expected.
Basically
1. to record: `roborazzi.test.record=true`, setting it to false does nothing
2. to verify: `roborazzi.test.verify=true`, setting it to false does nothing

Since they are mutually exclusive, I think it'd make sense to use `roborazzi.test.record=true` or `roborazzi.test.record=false` only.

What do you think?

**Comment by takahirom** [comment]
I personally think the false flag is unnecessary because it doesn't change anything. However, for the sake of clarity in documentation, it might still be helpful to include an explanation of the false setting. Regarding the verifyAndRecordRoborazziDebug option, it's important to note that both record and verify need to be set to true.

**Comment by sergio-sastre** [comment]
> I personally think the false flag is unnecessary because it doesn't change anything. However, for the sake of clarity in documentation, it might still be helpful to include an explanation of the false setting. Regarding the verifyAndRecordRoborazziDebug option, it's important to note that both record and verify need to be set to true.

Oh I see. That makes sense!
I think once this is documented, feel free to close this ticket.
Btw, +1 for Roborazzi for supporting this out of the box 😉

**Comment by takahirom** [comment]
@sergio-sastre 
Thanks! 
I've created a document for this. Please let me know if there's any room for improvement. 
https://github.com/takahirom/roborazzi#apply-roborazzi-gradle-plugin
