### ISSUE TITLE
Allow separate directories for golden screenshots & comparison images

### ISSUE THREAD

**Issue by simonwalter** [takahirom/roborazzi#125]
Is there a way to specify separate directories for the golden screenshots and the comparison images?

### Background
In our project, we use the `outputDirectoryPath` option to specify where golden screenshots should be stored. Currently, we specify a directory outside of `/build` and commit the generated files to Git using Git LFS. Here's an example:

```kotlin
class RuleTestWithPath {
  @get:Rule
  val roborazziRule = RoborazziRule(
    options = Options(
      outputDirectoryPath = "screenshots/custom_outputDirectoryPath",
      ...
    ),
  )
```
![image](https://github.com/takahirom/roborazzi/assets/5316135/f0b02dc9-bebc-4818-9b8e-02be10ca68be)

However, one limitation of using `outputDirectoryPath` is that the images generated by `verifyRoborazziDebug` for failing tests will also be put into the same folder: 

![image](https://github.com/takahirom/roborazzi/assets/5316135/caad893f-6ef2-4a95-a01d-22450497ca74)

While keeping the golden screenshots stored in the path specified by `outputDirectoryPath`, we would prefer to have the comparison images located inside the `/build` folder. This approach offers the following advantages:
- It helps to prevent accidental commits of the comparison files to Git, eliminating the need for manual deletion of the comparison files.
- When golden screenshots and comparison files are already separated, it becomes easier to store only the comparison images in our CI system for reviewing each run.

**Comment by takahirom** [comment]
Thank you for your suggestion. As a temporary workaround, you might be able to use the "_compare.png" naming convention that Roborazzi automatically applies to the generated files. These files could be moved to the desired location using a hook in the build task or something similar.

For more effective management of the golden screenshots and comparison files, what are your thoughts on introducing an additional option such as comparisonOutputPath to the Rule, alongside outputDirectoryPath? This wouldn't automate the relocation of files, but it could assist in specifying distinct paths for the golden screenshots and the comparison images.

**Comment by takahirom** [comment]
I'm considering extending the FileProvider, but it could lead to a rather complex implementation. As an alternative, what if we create a FileOutputInterceptor as a parameter to the Rule, like this?

```kotlin
sealed interface FileType {
  class Reference : FileType
  class Comparison : FileType
  class Actual : FileType
}

fun interface OutputFileInterceptor {
  fun intercept(fileType: FileType, original: File): File {

  }
}
```

**Comment by simonwalter** [comment]
I have the feeling that `OutputFileInterceptor` might be too complex just for updating the directory path. But I don't know if you already have other use cases for it in mind 🙂 

Why not always store the comparison images (_actual, _compare) inside of the `/build` folder and use "outputDirectoryPath" just for the golden screenshots. In my opinion the comparison images are part of the test report.

**Comment by takahirom** [comment]
You make a compelling point. Given our reliance on the Gradle Input file for our task, we're compelled to specify certain input and output folders in the Gradle settings to circumvent unexpected task skipping. Naturally, having the flexibility to set the path as desired would be convenient, but it calls for careful consideration. Moreover, considering that Roborazzi is likely to be adopted by larger organizations that often use Bazel, which may have different output paths, it seems we may indeed need to provide an option for users to set custom paths. So ideally, it might be best if we have a default output path to build/outputs/roborazzi, but also allow it to be customizable. Would that be correct?

**Comment by takahirom** [comment]
Let me summarize:

Current default behavior:

```
/build/outputs/roborazzi
  - screen.png
  - screen_compare.png
  - screen_actual.png
```

Your case with outputDirectoryPath:

```
/src/main/java/xxx/
  - screen.png
  - screen_compare.png
  - screen_actual.png
```

Bazel user with outputDirectoryPath:

```
/xxxx/screenshots
  - screen.png
  - screen_compare.png
  - screen_actual.png
```

---

The proposed change in behavior:

Default:

```
/build/outputs/roborazzi
  - screen.png
  - screen_compare.png
  - screen_actual.png
```

Your case with outputDirectoryPath:

```
/build/outputs/roborazzi
  - screen_compare.png
  - screen_actual.png

/src/main/java/xxx/
  - screen.png
```

Bazel user with outputDirectoryPath and new option:

```
/xxxx/screenshots
  - screen.png
  - screen_compare.png
  - screen_actual.png
```

**Comment by simonwalter** [comment]
> So ideally, it might be best if we have a default output path to build/outputs/roborazzi, but also allow it to be customizable. Would that be correct?

Yes, I think it makes sense to use `/build` as default and make it customizable 👍

**Comment by simonwalter** [comment]
What do you think about specifying the `outputDirectoryPath` in `CompareOptions` and `RecordOptions` inside of `RoborazziOptions`?

**Comment by takahirom** [comment]
Thank you. I was considering using the options parameter of Rule, but this is a better approach because it allows for changes each time captureRoboImage() is called.

**Comment by takahirom** [comment]
I've released this at https://github.com/takahirom/roborazzi/releases/tag/1.5.0-alpha-1 🙏
