### ISSUE TITLE
A way to resize a font scale?

### ISSUE THREAD

**Issue by hellohj** [takahirom/roborazzi#127]
I'm trying to replace our exiting Paparazzi snapshot testing with Roborazzi. 
One of important requirements for us is to test different font scales (1.0 to 2.0; up to 200% to meet WCAG guideline). 
Paparazzi provides a way to do like below for example, but I don't seem to find an available `RoborazziOptions`. 
Could you please tell me if there is an option to try out? If not, can we please add it to test a11y? Thanks. 
` @get:Rule
  val paparazzi =
    Paparazzi(
      deviceConfig =
        DeviceConfig.PIXEL_5.copy(fontScale = 2.0f))
`

**Comment by jisungbin** [comment]
Since Roborazzi uses Robolectric, we can use Robolectric's `@Config` and `RuntimeEnvironment`.

- `@Config(fontScale = user_font_scale)`
- `RuntimeEnvironment.setFontScale(user_font_scale)`

**Comment by takahirom** [comment]
Please let me know if the issue persists. I'll close this issue now as it appears to be resolved.

**Comment by hellohj** [comment]
It works like a charm. Thank y'all for the help!
