### ISSUE TITLE
Applying to dynamic feature modules

### ISSUE THREAD

**Issue by shashachu** [takahirom/roborazzi#142]
I noticed when trying to apply the roborazzi plugin to a dynamic feature module that it silently failed. Can you think of a reason why roborazzi wouldn't work in DFMs? Naively, at minimum it's missing a check here: https://github.com/takahirom/roborazzi/blob/c3800890ba60c9467bb4d864f30545d843b1c430/include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt#L273

**Comment by takahirom** [comment]
It's not that I have an intention not to support it, I just personally don't use dynamic features. I think it should be possible. By adding a sample module and appending the code for setting tasks to the part of the code you've pasted, I believe it should be complete.

**Comment by takahirom** [comment]
@shashachu 
I'll do it later, but I'm busy with things like DroidKaigi right now. Would you be willing to contribute if it's okay with you?

**Comment by shashachu** [comment]
sure, I can probably put up a PR next week.

**Comment by takahirom** [comment]
I attempted to add the sample but encountered an issue. It appears that Robolectric doesn't support dynamic feature modules. Given the circumstances, there's likely nothing we can do within this project. Therefore, I'm going to close this for now. We'll address the issue as soon as Robolectric adds support for dynamic feature modules.
https://github.com/robolectric/robolectric/issues/5597
