### ISSUE TITLE
Roborazzi and SDK 34

### ISSUE THREAD

**Issue by hellohj** [takahirom/roborazzi#150]
I wonder if there have been any previous reports of Roborazzi not working properly with Android SDK 34. We recently upgraded our SDK to 34 and Roborazzi snapshot tests failed due to an incorrect typography. 
We use Lato from our theme, but snapshots returned Roboto (Google font) and tests failed. Interestingly, everything was fine, such as colors from snapshots in the light and dark modes, but the typography was missing. Reverting SDK 34 to 33 (and every SDK 34 dependent library as well) fixed the issue of failing snapshot testing. 
I have attached a screenshot for your reference. 
Please let me know if you have any questions or workarounds to try. Thank you.

Important note: we are a little behind so our current version of Roborazzi is 1.4.0.

![slack uikit components banner SKBannerRoborazziTest testSKBanner fontScale=1 _compare](https://github.com/takahirom/roborazzi/assets/8292050/615dff47-1645-4646-be07-ca1f24874a4c)

**Comment by takahirom** [comment]
I'm surprised Robolectric is actually working on SDK 34, as I thought it wasn't currently supported. 👀
Could you let me know if this still happens after SDK 34 gets officially supported?
https://github.com/robolectric/robolectric/issues/8404#issuecomment-1681074880

**Comment by takahirom** [comment]
Let me close for now.
