### ISSUE TITLE
[Seeking Ideas] Support for HTML Report Format

### ISSUE THREAD

**Issue by takahirom** [takahirom/roborazzi#153]
Currently, we don't offer support for HTML-based reports.  
I don't think we need an elaborate report file to start with.  
Here's a simple example:

```html
<table>
  <tr><td>File Name</td><td>Image</td></tr>
  <tr><td>fileName.png</td><td><img src='https://user-images.githubusercontent.com/1386930/246645185-579199d5-8e17-4f51-b990-de603ca36251.png' width='80%' /></td></tr>
</table>
```

<table>
  <tr><td>File Name</td><td>Image</td></tr>
  <tr><td>fileName.png</td><td><img src='https://user-images.githubusercontent.com/1386930/246645185-579199d5-8e17-4f51-b990-de603ca36251.png' width='80%' /></td></tr>
</table>

Any must-have features you'd like to see? Let me know!

**Comment by jeprubio** [comment]
I think a report in html when running roborazzi would be great, it could use something like materializecss.com to look great and generate all the files (html + pngs) under build/reports.

If roboelectric is configured with a device (as: `@Config(qualifiers = RobolectricDeviceQualifiers.Pixel5)`) the resulting *compare.png image seem too big and I think they should be scaled down when shown in such an html. I would probably show the image scaled in the html and then in original size once an image is clicked.

**Comment by takahirom** [comment]
> something like materializecss.com

Thanks for bringing this to my attention.
It seems that materializecss.com is abandonware, so considering a forked project might be a good idea.
https://materializeweb.com/

> I would probably show the image scaled in the html and then in original size once an image is clicked.

For now, I'm considering using width='80%' to appropriately resize the images.

**Comment by takahirom** [comment]
I made a sample report file.
[index.html.zip](https://github.com/takahirom/roborazzi/files/12642146/index.html.zip)

**Comment by takahirom** [comment]
> I think they should be scaled down when shown in such an html

I agree, and it's a great idea. However, I think it's better than nothing, so let's start by releasing it.
