### ISSUE TITLE
recordRoborazziDebug never ends if lottie animation iterates forever 

### ISSUE THREAD

**Issue by morux2** [takahirom/roborazzi#166]
Hello @takahirom!

I encountered an issue when using Roborazzi, Lottie, Showkase together.
If I set `LottieConstants.IterateForever` to LottieAnimation, gradle task never ends.

I think, this issue occurs only when using Showkase together.

Is there any ways to resolve the issue?

this is my sample project that reproduces the issue.
https://github.com/morux2/RoborazziPractice/pull/6

```kotlin
@Composable
fun MainScreen() {
    Column(
        modifier = Modifier.fillMaxSize(),
    ) {
        val composition by rememberLottieComposition(spec = LottieCompositionSpec.RawRes(R.raw.heart))
        LottieAnimation(
            composition = composition,
            iterations = LottieConstants.IterateForever
        )
    }
}

@Preview(name = "MainScreenPreview", group = "MainScreen", showBackground = true)
@Composable
fun MainScreenPreview() {
    MainScreen()
}
```

**Comment by takahirom** [comment]
I believe this issue is not directly related to Roborazzi, as it can occur independently of it. However, you can potentially pause the execution by setting LottieTask.EXECUTOR to a PausableExecutor instance, like so: LottieTask.EXECUTOR = PausableExecutor().
Like this.
https://stackoverflow.com/a/16208043/4339442
https://github.com/DroidKaigi/conference-app-2023/pull/1265/files#diff-d3dcb6b05a7f3fed461af2ae3ca773d93f80a2270b59e9c549d782729fb38622R43

**Comment by morux2** [comment]
@takahirom 

Thank you for your reply!

I found that the problem is due to Lottie. However, it resolved at https://github.com/airbnb/lottie-android/pull/1987.
I believe that the issue occurred because `caputureRoboImage()` method call ActivityScenario (not composeTestRule).

Therefore, when I rewrote it to the following code, the test passed.
https://github.com/morux2/RoborazziPractice/pull/6/files

Is this solution make sence?

**Comment by morux2** [comment]
also, should I add some handling to the EXECUTOR you pointed out? I
t seems to be reported as a problem with Paparazzi, but I haven't encountered any problems so far.
https://github.com/cashapp/paparazzi#lottie

**Comment by morux2** [comment]
also, should I add some handling to the EXECUTOR you pointed out? 
It seems to be reported as a problem with Paparazzi, but I haven't encountered any problems so far.
https://github.com/cashapp/paparazzi#lottie

**Comment by takahirom** [comment]
I'm not certain, but it appears that Lottie supports the Compose mechanism and may not support the Espresso mechanism, which is why it works. As for the EXECUTOR, I believe there's no need to modify it unless you encounter issues.
Let me close this 🙏
