### ISSUE TITLE
Setting RoborazziRule.Options( outputDirectoryPath ) globally

### ISSUE THREAD

**Issue by timothyfroehlich** [takahirom/roborazzi#171]
For my workflow in https://github.com/google/automotive-design-compose/pull/389 I've set `RoborazziRule.Options( outputDirectoryPath )` in my test to output the recorded screenshots to a path outside my build directory. While doing later work I realized that the regular `.captureRoboImage()` calls did not use `outputDirectoryPath`, so I had to add the same path to the `.captureRoboImage()` calls. 

There's basically a few convenience things that I'd like, to avoid having to duplicate code or write code to avoid the duplication.

1. Add the ability to set the `outputDirectoryPath` from outside the tests. I think this should be configurable via Gradle property (instead of the plugin extension) so that this could be changed in different run environments. I would assume the given path to be relative to the project's root directory. So for a project with an `app/` and `lib/` subprojects, setting the gradle path to `testdata/roborazzi` would result in the subprojects saving the screenshots to `app/testdata/roborazzi` and `lib/testdata/roborazzi`.

2. Have `captureRoboImage()` and related functions use the `outputDirectoryPath`, so that the path doesn't need to be specified over and over again.

3. Have `captureRoboImage()` and related have a default file extension (`.png`, etc).

4. Enable a LastImage property to be set (via Gradle property or roborazzi plugin extension) so that I could just enable it by default, defaulting to capturing `composeTestRule.onRoot()`.

Those would allow me to turn this:
```
class RenderHelloWorld {
    @get:Rule val composeTestRule = createAndroidComposeRule<ComponentActivity>()

    @get:Rule
    val roborazziRule =
        RoborazziRule(
            composeRule = composeTestRule,
            captureRoot = composeTestRule.onRoot(),
            options =
                RoborazziRule.Options(
                    outputDirectoryPath = "src/testDebug/roborazzi",
                    // Always capture the last image of the test
                    captureType = RoborazziRule.CaptureType.LastImage()
                )
        )

    @Test
    fun testHello() {
        with(composeTestRule) {
            setContent { HelloWorldDoc.mainFrame(name = "Testers!") }
            onNodeWithText("Testers!", substring = true)
                .assertExists()
                .captureRoboImage("src/testDebug/roborazzi/nodeWithText.png")
        }
    }
}
```

to this:

```
class RenderHelloWorld {
    @get:Rule val composeTestRule = createAndroidComposeRule<ComponentActivity>()

    @get:Rule
    val roborazziRule = RoborazziRule(composeRule = composeTestRule)

    @Test
    fun testHello() {
        with(composeTestRule) {
            setContent { HelloWorldDoc.mainFrame(name = "Testers!") }
            onNodeWithText("Testers!", substring = true)
                .assertExists()
                .captureRoboImage("nodeWithText")
        }
    }
}
```

That said, if anything, the first two requests would be the most helpful.

**Comment by takahirom** [comment]
Thank you for raising this issue. I'm contemplating implementing the output directory in the following manner:

```diff
fun View.captureRoboImage(
 ) {
   if (!roborazziEnabled()) return
   captureRoboImage(
-    file = File(filePath),
+    file = fileWithOutputDirectoryContext(filePath),
     roborazziOptions = roborazziOptions
   )
 }
 
+fun fileWithOutputDirectoryContext(filePath: String): File {
+  if (filePath.startsWith("/")) {
+    return File(filePath)
+  }
+  val outputDirectory = provideRoborazziContext().outputDirectory
+  val outputDirectoryAbsolutePath = File(outputDirectory).absolutePath
+  val filePathAbsolutePath = File(filePath).absolutePath
+  if (filePathAbsolutePath.startsWith("$outputDirectoryAbsolutePath/")) {
+    // Remove duplicated path
+    val prefixRemovedFilePath = filePathAbsolutePath.removePrefix("$outputDirectoryAbsolutePath/")
+    val savingFile = File(outputDirectory, prefixRemovedFilePath)
+    println("Roborazzi: $filePath is within the output directory. Consider using the relative path $prefixRemovedFilePath instead of $filePath.")
+    return savingFile
+  }
+  return File(outputDirectory, filePath)
+}
```


Though it's a rare case, there exists an issue. If you aim to specify an output path as output/output/hoge.png with the outputDirectory set to output, and you use captureRoboImage("output/hoge.png"), the file will actually be stored as output/hoge.png.
