### ISSUE TITLE
[Compose] Options set via RoborazziRule are ignored

### ISSUE THREAD

**Issue by kirill-kamakin** [takahirom/roborazzi#186]
captureRoboImage function for Compose found [here](https://github.com/takahirom/roborazzi/blob/6e4252beaf4e240787e9c71c173ad13058e96bf9/roborazzi-compose/src/main/java/com/github/takahirom/roborazzi/RoborazziCompose.kt#L17) does not use RoborazziContext like View functions do [here](https://github.com/takahirom/roborazzi/blob/6e4252beaf4e240787e9c71c173ad13058e96bf9/roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt#L35). Due to that, the change threshold set via rule is ignored by Compose tests.

**Comment by takahirom** [comment]
Thank you for reporting this!
