### ISSUE TITLE
Fix licensing

### ISSUE THREAD

**Issue by chrisbanes** [takahirom/roborazzi#2]
This repository is obviously a fork of Paparazzi, but contains none of the upstream license headers.

**Comment by takahirom** [comment]
Thank you for your comment.
You are right. I am using the Gradle plugin code. I want to add the license.
I don't think any other code uses Paparazzi's code. Is there anywhere else other than the Gradle plugin where you think so?
https://github.com/takahirom/roborazzi/blob/main/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt#L16

**Comment by takahirom** [comment]
Anyway, Even though I had written it in the source code, I did not specify it as my license, so I have added it to the README. Thanks for pointing this out to me.

https://github.com/takahirom/roborazzi/commit/c7ef27e66d84acd23e8be5a087dc39c2d3e90845

**Comment by takahirom** [comment]
If you still have any problems, please let me know and I will open it again.
