### ISSUE TITLE
Add a file name parameter to captureRoboImage

### ISSUE THREAD

**Issue by saket** [takahirom/roborazzi#202]
When roborazzi captures multiple images, it suffixes them with their indices: `test`, `test_1`, `test_2`, and so on. Using numbers for differentiating between screenshots isn't very useful. Can roborazzi add a parameter to `captureRoboImage()` (as an overload) to accept custom file names?

**Comment by takahirom** [comment]
Thanks for using Roborazzi.
I believe you can utilize the `filePath` parameter of `captureRoboImage()` method. You might want to specify `outputDir`. You can achieve this by setting the `outputDirectory` parameter in `RoborazziRule`, and by setting `roborazzi.record.filePathStrategy` to `relativePathFromRoborazziContextOutputDirectory`.
https://github.com/takahirom/roborazzi/blob/0e749d4c817929c19befa0109d9f0ec7d5a8fdc0/roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt#L34
https://github.com/takahirom/roborazzi#roborazzirecordfilepathstrategy

**Comment by takahirom** [comment]
However, it can be a bit cumbersome to specify the .png extension for the filePath each time. You could create a custom function to generate the file path, though it may not be the most elegant solution.

**Comment by takahirom** [comment]
We might be able to do it this way, but I'm not sure at the moment.

captureRoboImage(output: CaptureOutput)
fileName(fileName: String): CaptureOutput
filePath(filePath: String): CaptureOutput

// Then
captureRoboImage(fileName("xxxx"))

**Comment by saket** [comment]
Yep I'm specifying a custom `filePath` right now, but I wish I was able to use roborazzi's `DefaultFileNameGenerator.generateName()` for extracting the class name automatically.

**Comment by takahirom** [comment]
That makes sense. I'm considering adding a `roboOutputName()` function.  What are your thoughts on this?

https://github.com/takahirom/roborazzi/pull/205

```kotlin
  @Test
  fun roboOutputNameTest() {
    assert(roboOutputName() == "com.github.takahirom.roborazzi.sample.RuleTestWithPath.roboOutputNameTest")
  }
```

**Comment by saket** [comment]
Sure, lgtm!

**Comment by saket** [comment]
Hi, is it intentional that `roboOutputName()` doesn't use `roborazziContext.outputDirectory`?

**Comment by takahirom** [comment]
Hello,
Indeed, the roboOutputName() function is designed to generate the file name. To save the file with a relative path derived from roborazziContext.outputDirectory, you can use relativePathFromRoborazziContextOutputDirectory.
https://github.com/takahirom/roborazzi#roborazzirecordfilepathstrategy
