### ISSUE TITLE
Screen screenshots including dialogs

### ISSUE THREAD

**Issue by nelletto** [takahirom/roborazzi#224]
Hi,
I'm trying to write screenshot tests with roborazzi to test a bottomsheetdialogfragment, but every attempt I make makes me get a completely white screenshot. What am I doing wrong?

The test is very simple:
```KOTLIN
@Test
fun test() {
    launchFragment<MyBottomsheetDialogFragment>(
        themeResId = R.style.AppBaseTheme
    ).onFragment {
        onView(isRoot()).captureRoboImage()
    }
}
```
Where MyBottomsheetDialogFragment is a BottomSheetDialogFragment

**Comment by takahirom** [comment]
Thanks. I've encountered a similar issue with Compose before, and we managed to resolve it.
https://github.com/DroidKaigi/conference-app-2023/pull/1090#issuecomment-1706796300

Could you try applying these settings in Espresso?
https://github.com/android/testing-samples/blob/main/ui/espresso/MultiWindowSample/app/src/androidTest/java/com/example/android/testing/espresso/MultiWindowSample/MultiWindowTest.java#L151

**Comment by sergio-sastre** [comment]
@nelletto 
Dialogs as well as BottomSheets are drawn in a different window.

Fortunately, Roborazzi supports capturing bitmaps.

so what you can do is to capture a bitmap of the dialog/bottomsheet for the screenshot, as here 
https://github.com/sergio-sastre/Android-screenshot-testing-playground/blob/master/dialogs/roborazzi/src/test/java/com/example/road/to/effective/snapshot/testing/dialogs/roborazzi/DeleteDialogParameterizedHappyPathTest.kt

**Comment by takahirom** [comment]
I have received several requests to take screenshots that include dialogs. Therefore, I am considering adding a captureScreenRoboImage() function. Do you have any thoughts on this?
https://github.com/takahirom/roborazzi/pull/225

**Comment by sergio-sastre** [comment]
> I have received several requests to take screenshots that include dialogs. Therefore, I am considering adding a captureScreenRoboImage() function. Do you have any thoughts on this? #225

You could use the kotlin view.drawToBitmap() method under the hood, although keep in mind that it uses Canvas under the hood, so if Robolectric Native Graphics supports drawing shadows and elevation in the future, Canvas will not draw them (pixel copy would though).

Moreover, I think one of the issues I faced was to use Dump mode with UI elements in another window, and I had to workaround it by adding the view of that window to the Activity, like here:
https://github.com/sergio-sastre/Android-screenshot-testing-playground/blob/master/dialogs/roborazzi/src/test/java/com/example/road/to/effective/snapshot/testing/dialogs/roborazzi/accessibility/AccessibilityTest.kt

Athough it works, the Activity window is larger than the Dialog window so the view is also a bit larger, but, ey, it works!

my point is: while providing such a method, which I find it  useful, keep DUMP mode in mind 😉

**Comment by takahirom** [comment]
Thank you for your feedback. I've made some modifications to utilize pixel copy as much as possible. Regarding dump mode, I believe we can capture screenshots with multiple windows in the PR using the Espresso Oracle class. Also, thank you for utilizing dump mode!

**Comment by takahirom** [comment]
I've added the captureScreenRoboImage() function to address this issue. Could you take a look? [Roborazzi 1.9.0-alpha-1 Release](https://github.com/takahirom/roborazzi/releases/tag/1.9.0-alpha-1)

**Comment by sergio-sastre** [comment]
> I've added the captureScreenRoboImage() function to address this issue. Could you take a look? [Roborazzi 1.9.0-alpha-1 Release](https://github.com/takahirom/roborazzi/releases/tag/1.9.0-alpha-1)

Sure!
But I won’t be able to give feedback till 3rd January 2024 though.

**Comment by marianeum** [comment]
@takahirom I tried out the latest alpha release and it works great for dialogs, but i'm still getting an empty snapshot for a modal bottom sheet (in compose)

**Comment by takahirom** [comment]
@marianeum Thanks for reporting this issue.
I was able to show the dialog. Could you try using `composeTestRule.waitForIdle()` to wait for the sheet to be displayed?
https://github.com/takahirom/roborazzi/pull/237#issuecomment-1874839363

**Comment by marianeum** [comment]
Hmm I already had a `waitForIdle` - I'm using the material3 version - I did a quick test with the material 2 version and that works for me as well, but not the material 3 one

**Comment by marianeum** [comment]
Also if it helps I'm seeing the same issue for `ExposedDropdownMenu` also in material 3 (the dropdown is not shown)

**Comment by takahirom** [comment]
@marianeum 
Thank you!
It appears that Material3 Compose dialogs exist within WindowManager, yet they lack a Window instance. As such, we may need to employ the View's draw method instead.
I have developed a temporary solution for this issue. Please await the upcoming release 🙏.
https://github.com/takahirom/roborazzi/pull/237

**Comment by marianeum** [comment]
Thank you for the speedy fix!

**Comment by takahirom** [comment]
@marianeum 
I saw your PR and it was impressive how you reduced the CI time to just 7 minutes with Roborazzi, down from up to 40 minutes! Can I mention this pull request in the upcoming podcast?
https://github.com/Skyscanner/backpack-android/pull/1840

**Comment by marianeum** [comment]
Yes of course :) thank you again for the quick fix!
