### ISSUE TITLE
Seeking guidance in integrating an isolated example   

### ISSUE THREAD

**Issue by TonyTangAndroid** [takahirom/roborazzi#23]
Hi there,

I have been playing around this library by checking out the whole repo locally and running it locally. I also made effort in creating a full isolated app to play around the library.

However, I could not figure out the effectiveness of this library.
To start with, I could not find any snapshot view generated under `build/outputs/roborazzi` .
Then , how would it catch a bug if I purposefully break the code?   Running `./gradlew recordRoborazziDebug` or ` ./gradlew verifyRoborazziDebug`  does not break at all matter how I change the code.

I think there must be gap that I failed to interpret it by following the readme.
 

I tried to find any other sample app that is using `Roborazzi`. But I only find `coil` library, which is large. Hence, I did not explore it further. 
Could you kindly check out this sample here  https://github.com/TonyTangAndroid/HelloRoborazzi and see to the gap?

It would be great that we could have a minimum app to demonstrate how `Roborazzi` is working.

**Comment by takahirom** [comment]
Thank you for your feedback and for providing the sample code. I checked, and it seems that your robo module was not applied with the roborazzi plugin. To take a screenshot, we need to use the plugin.
I have created this PR:
https://github.com/TonyTangAndroid/HelloRoborazzi/pull/3

Please run:
./gradlew robo:recordRoborazziDebug

As for the test not failing, we are currently only generating images for comparison, not causing the test to fail. I plan to address this issue by separating the compare and verify Gradle tasks in another PR.

**Comment by takahirom** [comment]
As far as samples go, I believe the app module in this repository is currently reasonably simple. Please let me know if there are other problems and I will open this issue again.

**Comment by TonyTangAndroid** [comment]
I see.  I think I know the gap now. 
`we are currently only generating images for comparison, not causing the test to fail.`.

Thank you for the clarification. 

I had the wrong assumption that since it is built for test purpose, hence it will fail if I introduce regression. And I had tried it out all the ways but failed to make it fail.
I forked this library and purposefully added a breaking change. Then it turned out that it still passed the CI. https://github.com/TonyTangAndroid/roborazzi/pull/2/files 

Looking forward to the feature  `separating the compare and verify Gradle tasks in another PR.`

**Comment by TonyTangAndroid** [comment]
I figured it out the baseline now. Will revise my sample app to make it simpler!

**Comment by takahirom** [comment]
Thank you for trying it out! Please let me know if there is anything else for improvement.

**Comment by alexjlockwood** [comment]
+1 Having tests fail when running the verification task would be ideal :)

**Comment by takahirom** [comment]
@TonyTangAndroid @alexjlockwood 

I will add the feature to the next release, possibly version 1.1.0-alpha-1.
https://github.com/takahirom/roborazzi/pull/28

Could you please check if this is the functionality you were looking for?

Running ./gradlew compareRoborazziDebug will generate a report file.
![image](https://user-images.githubusercontent.com/1386930/232952856-d30d3ec2-66cf-4cba-a27b-619da6e2e65b.png)

And `./gradlew verifyRoborazziDebug` verify the result (the task depends on compareRoborazziDebug)
![image](https://user-images.githubusercontent.com/1386930/232952384-ac4f082e-38eb-49bc-b0cb-8a7956038800.png)

**Comment by takahirom** [comment]
In any case, we can make changes since it's only an alpha version. I'm going to proceed with the release. Thank you for your feedback.

**Comment by alexjlockwood** [comment]
Is there a reason Roborazzi can't simply fail the unit test if it detects that the verification task has failed? Seems like it could be simpler than printing out a custom JSON object with all of the details the way you are currently doing it. And it would integrate much easier with our CI if we could just rely on unit tests passing or failing when screenshots differ by a certain amount. But I'm not sure the reason for your approach with the JSON file...

**Comment by takahirom** [comment]
Thanks.
The reason I was originally trying to keep the test from failing with verify was not to make it fail, but to use it to comment the compare image in the Pull Request.

However, since we are already checking to see if there have been any changes during the test, I think it would be fairly easy to make the test fail if there are changes during the test.

I feel there is probably a tradeoff to this. If you let the test fail at the time of that change, you will not know all the incomplete changes if there are multiple captures in a single test. On the other hand, failing the test allows us to know the results earlier and makes it easier to identify where the problem was from the stack trace.
Maybe it would be nice to have the option to choose, but I think that would complicate things a bit, so I'm giving it some thought.

**Comment by takahirom** [comment]
How about adding something like failImmediatelyIfChange: Boolean as an argument?
I think you'll need to prepare an extension to be used commonly across tests.

**Comment by takahirom** [comment]
As a point of sharing, the reason why I am taking the json approach is because I think it is easier to create something like the following.
<img src=https://user-images.githubusercontent.com/1386930/233220704-bbbb6687-67bf-45a7-b6eb-699a5437c7db.png width=200 />

**Comment by takahirom** [comment]
I'm starting to think that it's a good idea to make the verify task fail at an earlier stage since those who want to compare can use the compare task.

**Comment by TonyTangAndroid** [comment]
'Verify' indicates that it might fail. 'Compare' indicates it only show the difference.  This is impeccable.

**Comment by takahirom** [comment]
Thanks.
Do you think we should fail the test even if we just add an image?

**Comment by TonyTangAndroid** [comment]
Failing is better than surprises. Developers could record it again if the added image is expected to establish a new baseline. The general idea is to make it cheap to have a trustful baseline.

**Comment by takahirom** [comment]
Thank you. I've done that and made it customizable as well.
https://github.com/takahirom/roborazzi/pull/35/files#diff-00ce4fe2bc5d20ec09ebb4b88b8b86c493377ad9f0f7e423d7eb2caf906ca6caR267

**Comment by alexjlockwood** [comment]
I've tested the verify task on `1.1.0-alpha-3` and I'm still not able to see that the test or task fails 🤔

**Comment by takahirom** [comment]
I will check this issue again, but in the meantime, could you provide a minimal reproducible code sample? This would help us better understand and address the problem more effectively.

**Comment by takahirom** [comment]
Thank you for pointing out the issue. It seems that the verify task might have been broken when I implemented support for configuration cache, causing it not to work. I am currently working on a fix along with tests to ensure that the verify task functions correctly.

**Comment by takahirom** [comment]
I am releasing it. Apologies for any inconvenience caused.

**Comment by takahirom** [comment]
Could you try 1.1.0-alpha-4?
https://github.com/takahirom/roborazzi/releases/tag/1.1.0-alpha-4

**Comment by alexjlockwood** [comment]
@takahirom Thank you, it works now!
