### ISSUE TITLE
Tests succeeding locally but failing in the build pipeline

### ISSUE THREAD

**Issue by beshoy-samy** [takahirom/roborazzi#233]
Hi guys I am facing a weird issue where the tests are succeeding locally but failing in the build pipeline
here is one of the compared images.

It seems there is no difference between the reference and the new one, so what could be the issue here? 🤔 

I am using the latest version `1.9.0-alpha-2`

<img src="https://github.com/takahirom/roborazzi/assets/16430789/02bc4b4b-2ee2-4dfc-94b1-78767c2ce5fe" />

**Comment by takahirom** [comment]
@beshoy-samy 
Thank you for reporting this issue. Do you take reference screenshots in different environments? This is important because it appears that Robolectric Native Graphics renders differently across various operating systems.
https://github.com/robolectric/robolectric/issues/8457

**Comment by takahirom** [comment]
Roborazzi offers two options for comparing images:

Percentage of Changed Pixels
Percentage of Color Difference
You can set these in the 'Compare Options' menu.
If you would like to accept these changes, please select these options.
https://github.com/takahirom/roborazzi/blob/main/include-build/roborazzi-core/src/commonJvmMain/kotlin/com/github/takahirom/roborazzi/RoborazziOptions.kt#L164

**Comment by beshoy-samy** [comment]
@takahirom yep thanks a lot I did go around it using these options
