### ISSUE TITLE
Migrating from the org.json Library to Gson

### ISSUE THREAD

**Issue by takahirom** [takahirom/roborazzi#236]
Why?
* Using the org.json library requires manual mapping for each class, which is time-consuming.
* Vulnerabilities in the org.json library appear frequently, making it difficult to maintain.
* Since AGP also utilizes Gson, consolidating to a single library helps avoid the introduction of numerous libraries.

**Comment by sanao1006** [comment]
I would like to work on this issue!

- Migrating the `org.json` Library to `Gson`
- Pass all `CaptureResultTest` tests

Are there any other tasks that need to be completed in order to resolve this issue?
(E.g., pass tests for `sample-android`, etc.)

**Comment by takahirom** [comment]
Thanks! I think that's all you have to do to solve this issue.
