### ISSUE TITLE
1.8 alphas are not present on maven central

### ISSUE THREAD

**Issue by ZacSweers** [takahirom/roborazzi#242]
```
- Plugin Repositories (could not resolve plugin artifact 'io.github.takahirom.roborazzi:io.github.takahirom.roborazzi.gradle.plugin: 1.8.0-alpha-2')
  Searched in the following repositories:
    MavenRepo
    Google
    Kotlin-Bootstrap(https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev/)
    Compose-JB(https://maven.pkg.jetbrains.space/public/p/compose/dev)
    Gradle Central Plugin Repository
```

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
I believe there are POM files in Maven Central. 👀 
Do you have a repository that can reproduce this issue?

https://s01.oss.sonatype.org/service/local/repositories/releases/content/io/github/takahirom/roborazzi/io.github.takahirom.roborazzi.gradle.plugin/1.8.0-alpha-2/io.github.takahirom.roborazzi.gradle.plugin-1.8.0-alpha-2.pom
https://s01.oss.sonatype.org/service/local/repositories/releases/content/io/github/takahirom/roborazzi/roborazzi-gradle-plugin/1.8.0-alpha-2/roborazzi-gradle-plugin-1.8.0-alpha-2.pom
https://s01.oss.sonatype.org/service/local/repositories/releases/content/io/github/takahirom/roborazzi/roborazzi-gradle-plugin/1.8.0-alpha-2/roborazzi-gradle-plugin-1.8.0-alpha-2.jar

**Comment by ZacSweers** [comment]
It's working for me now, it looks like maven central had an outage earlier when I tried 😓
