### ISSUE TITLE
Android unit tests in compose multiplatform project don't capture dialogs

### ISSUE THREAD

**Issue by ZacSweers** [takahirom/roborazzi#245]
Repro: https://github.com/slackhq/circuit/pull/1121

Version: `1.9.0-alpha-1`

File: `circuitx/overlays/src/androidUnitTest/kotlin/com/slack/circuitx/overlays/OverlaySnapshotTests.kt`

I'm unable to consistently get this project to capture snapshots. Even when they do get generated however, they do not contain dialogs shown on the screen, instead only showing a white background. This is even with using the new `captureScreenRoboImage()` API.

**Comment by takahirom** [comment]
Could you try updating the version? The capture dialogs have undergone some logic changes.

**Comment by takahirom** [comment]
I will close this issue since it has been fixed.

**Comment by ZacSweers** [comment]
Can you clarify which version you updated to?

**Comment by ZacSweers** [comment]
Tried with 1.9.0-alpha-4 but finding that `./gradlew :circuitx:overlays:recordRoborazziRelease` does not produce any new snapshots in that linked repro 🤔

**Comment by ZacSweers** [comment]
Oh, I see them under `build/outputs/roborazzi`, even though I specify a custom path in `RoborazziOptions` 🤔 

```kotlin
private val roborazziOptions =
  RoborazziOptions(
    compareOptions =
      CompareOptions(changeThreshold = 0F, outputDirectoryPath = "src/androidUnitTest/snapshots"),
  )
```

Does `captureScreenRoboImage()` not support this?

**Comment by ZacSweers** [comment]
I'm able to work around it by specifying a manual filePath param each time, but that seems quite tedious to have to do for each test. I'm also seeing an odd behavior where roborazzi still generates (old) snapshot tests to the build/outputs/roborazzi dir (there is no more `test()` function, the `bottomSheet()` uses an old UI, etc)

<img width="442" alt="image" src="https://github.com/takahirom/roborazzi/assets/1361086/360565ff-986d-4ae2-baf0-c36ad492dc8a">

**Comment by takahirom** [comment]
Thank you. Indeed, that's true. I'm a bit busy today, so I'll take a look at it tomorrow. In the meantime, could you try this? https://github.com/takahirom/roborazzi?tab=readme-ov-file#roborazzirecordfilepathstrategy

**Comment by takahirom** [comment]
I've figured out what was happening. The `outputDirectoryPath` in `CompareOption` is the location for outputting the compare files, not for setting the file paths of regular image files. Currently, if you want to do this, you need to use `RoborazziRule` or specify it directly. If you want to specify directly without having to create your own file names, you can use `roboOutputName()` with `captureScreenRoboImage()`.

```kotlin
fun yourOutputPath(additionalText: String = ""): String {
  return "src/androidUnitTest/snapshots" + roboOutputName() + additionalText + ".png"
}
```
