### ISSUE TITLE
Empty screenshots

### ISSUE THREAD

**Issue by victorpineda-jt** [takahirom/roborazzi#246]
After migrating from Paparazzi to Roborazzi 1.8.0-rc-2, I'm getting empty screenshots from all my tests. The record step is completed successfully, and the png files are created, but when I review them, they are completely empty, with no content rendered, just a blank container. I've changed the GraphicsMode annotation from NATIVE to LEGACY to get more info about the components rendered, and all I see is this:

![com jobandtalent companies feature shifts editshift screenshots PublishDialogScreenshotTest_publishDialogTest](https://github.com/takahirom/roborazzi/assets/155441962/6bf5b5ac-e8a0-46e5-82e0-52369a804690)

On the other hand, Paparazzi was rendering the whole content without problems. I've tried capturing the image in different ways with the same result, like:

````
  captureRoboImage {
            content()
  }
  ````
  
  or
  
  ````
    @get:Rule
    val composeRule = createComposeRule()
    
    ...
    
    composeRule.setContent{ content() }
    composeRule.onRoot().captureRoboImage()
````
    
   
I've also tried different robolectric devices using @Config(qualifiers = RobolectricDeviceQualifiers.Pixel5) but I still get empty screenshots. 
    
My build.gradle file is also including andorid resources like this:
    
````
     testOptions {
        animationsDisabled = true
        unitTests {
            isIncludeAndroidResources = true
        }
    }
````
    
 Any idea what is going on here?

**Comment by takahirom** [comment]
Thanks for trying out!
To take screenshots, please use Robolectric 4.10 alpha 1 or later and please add @GraphicsMode(GraphicsMode.Mode.NATIVE) to your test class. 🙏 
https://github.com/takahirom/roborazzi?tab=readme-ov-file#add-roborazzi

**Comment by takahirom** [comment]
Sorry, I think I misunderstood this question

**Comment by takahirom** [comment]
You may need to use a newer SDK to capture the screenshots. Could you try using SDK version 33 or a similar one? For more information, visit: https://github.com/takahirom/roborazzi/issues/114#issuecomment-1627666632

**Comment by victorpineda-jt** [comment]
@takahirom thanks for the quick response, I've already solved it by doing that 👏
