### ISSUE TITLE
Is roborazzi release 1.9.0 published?

### ISSUE THREAD

**Issue by desugar-64** [takahirom/roborazzi#251]
Is roborazzi release 1.9.0 published?
https://github.com/takahirom/roborazzi/releases/tag/1.9.0

> * Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'io.github.takahirom.roborazzi', version: '1.9.0', apply: false] was not found in any of the following sources:

**Comment by desugar-64** [comment]
1.9.0-alpha04 works just fine

**Comment by takahirom** [comment]
Sorry, not yet. I'll release it today.

**Comment by takahirom** [comment]
It should be released. Please check it out!
