### ISSUE TITLE
Raborazzi 1.9.0 + Robolectric 4.12-SNAPSHOT

### ISSUE THREAD

**Issue by desugar-64** [takahirom/roborazzi#255]
Understanding Rendering Outputs with Raborazzi and Robolectric

I'm currently working with the following setup:

    Raborazzi Version: 1.9.0
    Robolectric Version: 4.12-SNAPSHOT
    Jetpack Compose Version: 1.6.0

Issue Encountered: When I enable hardware rendering (RNG HW) by setting `System.setProperty("robolectric.screenshot.hwrdr.native", "true")`, I am encountering an issue where the rendering output results in an empty (black) screenshot. Is this a known limitation, and is the feature not yet supported?

Additional Context:
Methods Used: `captureScreenRoboImage()` and `captureOnRoot()`.
Primary Concern: I am awaiting hardware rendering capabilities due to a clipping-to-outline issue in Jetpack Compose 1.6.0.

Any insights or suggestions regarding this issue would be greatly appreciated.

**Comment by takahirom** [comment]
We are discussing the RNG HW here. I have the code which can reproduce the issue using Espresso, but we haven't found a solution yet.
https://github.com/robolectric/robolectric/issues/8081#issuecomment-1886067581

**Comment by takahirom** [comment]
@desugar-64 (CC: @chrisbanes )
I've tested the hardware rendering (RNG HW) with the current snapshot version, and it performs excellently.
https://github.com/takahirom/roborazzi/pull/273#issuecomment-1970759554

Could you please confirm if you're utilizing ShadowPackageManager.addActivityIfNotPresent or something in your tests?
https://github.com/robolectric/robolectric/issues/8081#issuecomment-1968280166

**Comment by chrisbanes** [comment]
It's working nicely for me! https://github.com/chrisbanes/haze/pull/147

**Comment by serhiiyaremychecw** [comment]
Wow, let me check this too.

**Comment by serhiiyaremychecw** [comment]
@takahirom 
Yay, I can confirm HW rendering is working and my composable functions are no longer clipped to bounds!

**Comment by serhiiyaremychecw** [comment]
You can close the issue.

**Comment by takahirom** [comment]
Thank you for your feedback. I've closed this issue and included the information in the FAQ: https://github.com/takahirom/roborazzi?tab=readme-ov-file#q-the-images-taken-from-roborazzi-seem-broken
