### ISSUE TITLE
TooltipBox is not displayed on screenshot

### ISSUE THREAD

**Issue by nelson-glauber** [takahirom/roborazzi#258]
I'm trying to write a screenshot test for a `TooltipBox` but the tooltip is not being drawn on the screenshot image.
Here's the code that I'm using...
```kotlin
Box(
    Modifier
        .size(200.dp)
        .background(Color.Green)
        .testTag(testTag)) {
    TooltipBox(
        positionProvider = TooltipDefaults.rememberPlainTooltipPositionProvider(),
        state = rememberTooltipState(initialIsVisible = true, isPersistent = true),
        tooltip = {
            PlainTooltip {
                Text(text = "Tooltip")
            }
        },
        content = {
            Text(text = "Content")
        }
    )
}
```
And I'm using:
```
composeRule.onNodeWithTag(testTag, useUnmergedTree = true).captureRoboImage()
```
I also tried the code below without the `testTag`, but didn't work as well...
```
composeRule.onRoot().captureRoboImage()
```
More info:
```
android-gradle-plugin = "8.2.2"
androidx-compose-bom = "2024.01.00"
androidx-compose-material3 = "1.2.0-rc01"
roborazzi = "1.9.0"
```

Here's the generated image by Roborazzi and an emulator screenshot
<img src="https://github.com/takahirom/roborazzi/assets/20464075/fa439237-43f3-44b8-bcbf-2832f3dc84d9" width=300 />

<img src="https://github.com/takahirom/roborazzi/assets/20464075/f860de3b-4e85-49d4-82b6-e20dd2997df0" />

**Comment by takahirom** [comment]
@nelson-glauber 
I'm not sure, but I think the tooltip might be in a different window. Could you try `captureScreenRoboImage()`?

**Comment by nelson-glauber** [comment]
It worked @takahirom. It drew the tooltip on top of the "ActionBar" :/
But it's fine. Thank you very much.

**Comment by takahirom** [comment]
I'm glad to hear that captureScreenRoboImage() worked for you, @nelson-glauber. While I'm closing this issue for now, I'm not entirely clear on the problem with the "ActionBar" and how the tooltip is interacting with it. If you encounter any patterns or specific issues related to this, please don't hesitate to let me know.

**Comment by nelson-glauber** [comment]
@takahirom Just for the record. This is what I meant with _"drew the tooltip on top of the "ActionBar"_.
<img src="https://github.com/takahirom/roborazzi/assets/20464075/c69f6d1e-2de2-455c-bfdd-e00299b4ce66" width=400 />
