### ISSUE TITLE
Incorrect screenshot of ShapeableImageView with parent padding

### ISSUE THREAD

**Issue by dalapenko** [takahirom/roborazzi#271]
Hello. When use Robarazzi for screenshot of view with ShapeableImageView which has parent with padding - I saw that screenshot has artefact like black border of image. When start application - view looks okay. I think that bug of robolectric's render, but  SoF or any else source hasn't good fix. May be you know what going going bad?

Of course I made sample of problem: https://github.com/dalapenko/ShapeableRobolecticBug

and in attachment screenshots of difference between view on device when start app and Robarazzi screenshot:

<details>
  <summary>view_on_device</summary>

![view_on_device](https://github.com/takahirom/roborazzi/assets/30049446/172be2bb-7650-4a54-ba4b-c4cd443c2b41)

</details>

<details>
  <summary>roborazzi_screenshot</summary>

![roborazzi_screenshot](https://github.com/takahirom/roborazzi/assets/30049446/def6641a-2859-4e07-9977-9fa420138c34)

</details>

**Comment by takahirom** [comment]
Thanks
This issue may be associated with Robolectric's hardware rendering. It appears that they are addressing it, so please wait for the time being. For more details, see: https://github.com/robolectric/robolectric/issues/8592

**Comment by takahirom** [comment]
@dalapenko 
Could you try using native graphics mode?
https://github.com/takahirom/roborazzi/issues/255#issuecomment-1972838571
