### ISSUE TITLE
Roborazzi gets stuck on Windows

### ISSUE THREAD

**Issue by JackEblan** [takahirom/roborazzi#285]
*Robolectric 4.12 adds support for the native runtime (native SQLite and graphics modes) on Windows x86_64* 

but when I tried it on my machine(Windows 10), it got stuck and I cannot run any Roborazzi tasks.

**Comment by takahirom** [comment]
@JackEblan I was able to verify that it works in the GitHub Actions Windows environment. Could you elaborate on where you got stuck? Which task did you get stuck on?
https://github.com/takahirom/roborazzi/pull/287

**Comment by JackEblan** [comment]
@takahirom I am using the code from [nowinandroid](https://github.com/android/nowinandroid) with the help of this [ScreenshotHelper.kt](https://github.com/android/nowinandroid/blob/main/core/screenshot-testing/src/main/kotlin/com/google/samples/apps/nowinandroid/core/testing/util/ScreenshotHelper.kt) 

One of the developers from Nia faced some errors on Windows too in this [reply](https://github.com/android/nowinandroid/issues/1242#issuecomment-2028442582)

I'm still hoping I can ran screenshot tests locally. Maybe it's another issue from Robolectric or this. By the way, thank you🫡

**Comment by takahirom** [comment]
@JackEblan 
It seems that this issue is not related to Roborazzi, so I'll go ahead and close it. If you have any other issues, please let me know, and I'll be happy to reopen this one for you.
