### ISSUE TITLE
update robolectric version from 4.10.3 to 4.12.1

### ISSUE THREAD

**Issue by sanao1006** [takahirom/roborazzi#288]
## Overview
It would be possible to run roborazzi in a Windows environment by increasing the version of robolectric to 4.12.1.
https://github.com/robolectric/robolectric/releases/tag/robolectric-4.12.1

However, it looks like you have created some PRs[^1][^2][^3] and verified Roborazzi works in a Windows environment, so maybe there are still some concerns for the upgrade

What are some of the problems that need to be solved in order to increase the version of Robolectric?

### Note
@takahirom ,
I have a Windows PC, so if you tell me what you want to verify, I can verify it on my actual device, not a CI.

[^1]: https://github.com/takahirom/roborazzi/pull/287
[^2]: https://github.com/takahirom/roborazzi/pull/286
[^3]: https://github.com/takahirom/roborazzi/pull/273

**Comment by takahirom** [comment]
I'm open to updating Robolectric. So If you could create a PR, that would be much appreciated.
However, to my knowledge, we're using compileOnly, which means it's not utilized by end users.

**Comment by takahirom** [comment]
Technically, Robolectric is not included in Roborazzi's pom. Therefore, if users choose to use Roborazzi, they must incorporate their own version of Robolectric. This approach is intended to allow for future flexibility.
