### ISSUE TITLE
Automatic file naming with .captureRoboImage()

### ISSUE THREAD

**Issue by takahirom** [takahirom/roborazzi#3]
It is a pain to name a file every time I call a function, so I want to make it so that I don't have to name it somehow.
If possible, I would like to get the name of the method of the test well.

**Comment by sergio-sastre** [comment]
Looks like this is what you are looking for:
https://junit.org/junit4/javadoc/4.12/org/junit/rules/TestName.html

**Comment by takahirom** [comment]
I can work around it by using that, but it still seems tedious to have to create an index like i++ for tests when taking multiple shots within a single method.
I think it would be ideal to be able to define Rules and Runners and override settings in such a way that those with narrower scopes are given priority.
