### ISSUE TITLE
Support configuration cache

### ISSUE THREAD

**Issue by takahirom** [takahirom/roborazzi#30]
>4 problems were found storing the configuration cache, 3 of which seem unique.
> - Task `:app:compareRoborazziDebug` of type `io.github.takahirom.roborazzi.RoborazziPlugin$CompareReportGenerateTask`: invocation of 'Task.project' at execution time is unsupported.
>  See https://docs.gradle.org/7.6.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

Maybe it occurred here
https://github.com/takahirom/roborazzi/blob/main/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt#L124

**Comment by takahirom** [comment]
For now, you can work around it by adding `--no-configuration-cache` to the Gradle task.

**Comment by takahirom** [comment]
https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution 👀

**Comment by jisungbin** [comment]
As a workaround, maybe you can also use the following approach:

```kotlin
tasks.matching { task ->
    task.name.contains("roborazzi", ignoreCase = true)
}.configureEach {
    notCompatibleWithConfigurationCache("https://github.com/takahirom/roborazzi/issues/30")
}
```
