### ISSUE TITLE
Transparent image when use robolectric.screenshot.hwrdr.native and build activity by Robolectric

### ISSUE THREAD

**Issue by dalapenko** [takahirom/roborazzi#300]
Tried to use option robolectric.screenshot.hwrdr.native after new Robolectric release for resolve issue with shadows https://github.com/takahirom/roborazzi/issues/271 but faced with new problem. When I build some activity only for test and don't register it in AndroidManifest.xml manually - I got transparent image. I found your comment with similar problem https://github.com/robolectric/robolectric/issues/8081#issuecomment-1968280166 but may be you found any resolution or trick except add test only activity to AndroidManifes file in app?

I made [sample](https://github.com/dalapenko/ShapeableRobolecticBug/blob/main/app/src/test/java/tech/dalapenko/shapeablebug/MainActivityTest.kt) with problem: 

And try your [test](https://github.com/dalapenko/ShapeableRobolecticBug/blob/main/app/src/test/java/tech/dalapenko/shapeablebug/IssueTestClass.java) from issue - it failed too.

Test with robolectric 4.12.1 && roborazzi 1.11.0

**Comment by takahirom** [comment]
I don't have a good solution for this. You might consider looking into some alternatives.
https://github.com/robolectric/robolectric/pull/4736#issuecomment-1831034882
