### ISSUE TITLE
Migrate from Gson to KotlinX.Serialization

### ISSUE THREAD

**Issue by takahirom** [takahirom/roborazzi#305]
The project is currently using Gson for JSON serialization, which is not fully compatible with Kotlin Multiplatform. We've successfully migrated CaptureResult to KotlinX.Serialization in iOS module, but we still need to migrate CaptureResults and other related classes.
https://github.com/takahirom/roborazzi/blob/main/roborazzi-compose-ios/src/iosMain/kotlin/io/github/takahirom/roborazzi/CaptureResult.kt

**Comment by sanao1006** [comment]
Hi.
I will work on this issue! I will ask you questions when I have something I don't understand.

**Comment by takahirom** [comment]
Thanks for reaching out! Feel free to ask me anything.
