### ISSUE TITLE
captureRoboImage() of a View and Composable, without the need of ViewInteractions or SemanticNodes

### ISSUE THREAD

**Issue by sergio-sastre** [takahirom/roborazzi#33]
### The issue
Currently, Roborazzi depends heavily on Espresso and ComposeRule.

That's not the case with other screenshot testing frameworks, like Paparazzi, Shot, Dropshots...

In screenshot testing, it's also common to inflate a View without attaching it to an Activity. **If not attached, you cannot find it with Espresso, and therefore it would not be possible to screenshot it**.

Moreover, not attaching a View to an Activity has one extra advantage:
you can control its width and height to see how the View would render for different widths and heights.

That's something AndroidUiTestingUtils provides via `waitForMeasureView(exactWidthPx, exactHeightPx)`, like in [this example here](https://github.com/sergio-sastre/Android-screenshot-testing-playground/blob/master/dialogs/shot/src/androidTest/java/com/example/road/to/effective/snapshot/testing/dialogs/shot/parameterized/DeleteDialogWithParameterizedRunnerTest.kt), but it's not compatible with Roborazzi because of the reason I've described above.

### Desired Solution
Ideally, `captureRoboImage(view)` and `captureRoboImage(@Composable () -> Unit)` should be provided to enable such cases and become less Espresso/ComposeRule dependent.

Additionally, a similar option for bitmaps e.g. `captureRoboImage(bitmap)` would be also useful, since you can draw a bitmap out of a View/Composable but applying your own Bitmap options. Shot and Dropshots offer that as well.

**Comment by takahirom** [comment]
Thanks.
I think it is possible for Android View, probably because the View probably has a context and theme.
In the case of Compose, I think it is possible by doing ActivitySenario.launch, etc.
My question is in the case of View, how do you instantiate the View in your test?

**Comment by sergio-sastre** [comment]
That's the trick of `ActivityScenarioConfigurator.ForView()` and `ActivityScenarioConfigurator.ForComposable()`: They launch an activity with a specific configuration for locale, fontscale, uiMode... and use the context of that activity to inflate views -> the views inherit the configuration of that context ;)

I reommend you take the sample I mentioned previously:
[Dialog screenshot example](https://github.com/sergio-sastre/Android-screenshot-testing-playground/blob/master/dialogs/shot/src/androidTest/java/com/example/road/to/effective/snapshot/testing/dialogs/shot/parameterized/DeleteDialogWithParameterizedRunnerTest.kt)

To make it work with Roborazzi, you can use this method (as you can see, I need to attach the View, but it happens after using the `waitForMeasureDialog(exactWidthPx, exactHeightPx)`, so it does not take effect):
```kotlin
    fun View.asViewInteraction(
        activity: Activity,
    ): ViewInteraction {
        (activity.window.decorView.rootView as ViewGroup).addView(this)
        return onView(isRoot())
    }
```

And replace the `compareDialogScreenshot()` with this:
```kotlin
dialog
            .asViewInteraction(activity)
            .captureRoboImage(filePath("HELLO"))
```

So eventually you get this:
```kotlin
@RunWith(RobolectricTestRunner::class)
class DialogTest {

    @get:Rule
    val activityScenarioForViewRule =
        ActivityScenarioForViewRule(
            config = ViewConfigItem(
                locale = "en",
                uiMode = UiMode.DAY,
                orientation = Orientation.PORTRAIT,
                fontSize = FontSize.NORMAL,
                displaySize = DisplaySize.NORMAL,
            ),
            backgroundColor = Color.TRANSPARENT,
        )

    @Test
    fun snapDialog() {
        val deleteItem = HappyPathTestItem.NORMAL.deleteItem
        val activity = activityScenarioForViewRule.activity

        val dialog = waitForMeasuredView(exactWidthPx = deleteItem.dialogWidth.widthInPx) {
            DialogBuilder.buildDeleteDialog(
                ctx = activity,
                onDeleteClicked = {},
                bulletTexts = itemArray(activity, deleteItem.bulletTexts)
            ).window!!.decorView
        }

        dialog
            .asViewInteraction(activity)
            .captureRoboImage(filePath("DialogTest"))
    }

```

I hope it helps :)

**Comment by takahirom** [comment]
Thanks. Maybe as for testing for Roborazzi, Maybe I can just findViewById in Activity and use it.

**Comment by sergio-sastre** [comment]
Not quite what I had in mind.
That would not work for Dialogs (non-composable dialogs)

The Dialog is created with the Context of the Activity, but never attached to it, but in another window.

However, it is styled correctly because it used the Activity Context to be inflated.

To retrieve Dialogs view, it is as easy as dialog.window.decorView

The best option would be to provide sth like `view.captureRoboImage()`, and draw a Bitmap from the view itself.

kotlin-ktx already has an extension method for that:
[`view.drawToBitmap()`](
https://developer.android.com/reference/kotlin/androidx/core/view/package-summary)

**Comment by takahirom** [comment]
@sergio-sastre 
I've created a PR. I didn't see your comments. Could you please take a look at it?
https://github.com/takahirom/roborazzi/pull/42

**Comment by sergio-sastre** [comment]
@takahirom 
Sure, please give me till this evening to review it
