### ISSUE TITLE
Unexpected results when using with Compose Modifier.drawWithContent and BlendMode

### ISSUE THREAD

**Issue by adrinieto** [takahirom/roborazzi#352]
When using `Modifier.drawWithContent` and `BlendMode.BlendMode.SrcIn` I get a different result than in a real device or emulator. 
For example, this is the Compose code to build a partially filled star icon:

```kotlin
Icon(
	painterResource(R.drawable.ic_star), contentDescription = null,
	modifier = Modifier
	    .size(200.dp)
	    .drawWithContent {
	        drawContent()
	        drawRect(Color.Yellow, size = Size(size.width * 0.7f, size.height), blendMode = BlendMode.SrcIn)
	    },
	)
```

Here are some results I got using the sample Android app in `ComposeTest`.

If I use `createComposeRule`, that internally uses a `ComponentActivity` I get a square image.

```kotlin
  @get:Rule
  val composeTestRule = createComposeRule()
```

![image](https://github.com/takahirom/roborazzi/assets/908250/884098af-f07a-4a57-b99c-79d40faf4e2e)

But, If I use `RoborazziTransparentActivity` it works.

```kotlin
 @get:Rule
  val composeTestRule = createAndroidComposeRule<RoborazziTransparentActivity>()
```

![image](https://github.com/takahirom/roborazzi/assets/908250/1abe8531-d3bc-483c-935e-07537ce78df5)

After further investigation, it seems related with the `colorBackground`. It only works with a transparent background:

```xml
    <item name="android:colorBackground">@android:color/transparent</item>
```

When used in Compose Previews it works as expected, so I'm not sure what's going on.

Is this a problem of Roborazzi or a limitation of using Layoutlib?

Thanks in advance.

**Comment by adrinieto** [comment]
In case it helps, to make `BlendMode.SrcIn` work in Compose `.graphicsLayer(compositingStrategy = CompositingStrategy.Offscreen)` is also needed. But the result is the same with Roborazzi.

https://stackoverflow.com/a/69790654/1518996

**Comment by takahirom** [comment]
Cloud you try to use hardware rendering mode?
https://github.com/takahirom/roborazzi/issues/255#issuecomment-1972838571

**Comment by adrinieto** [comment]
Thanks for your fast response. It works! 🙌 

Should we enable this flag for all the project? Or only for specific screens? I see it also solves issues with elevations, shadows, and gradients. I guess there are some side effects and that's why it's not enabled by default.

**Comment by takahirom** [comment]
Good question! I think you can check this issue. I think we can enable the flag in the next Robolectric version for all projects
https://github.com/takahirom/roborazzi/issues/296
