### ISSUE TITLE
Provide an effective method for filtering between Roborazzi tests and non-Roborazzi tests

### ISSUE THREAD

**Issue by takahirom** [takahirom/roborazzi#36]
I have numerous tests in my project. I would like to run Roborazzi tests using ./gradlew recordRoborazziDebug only if it is a Roborazzi test and use ./gradlew testDebugUnitTest for non-Roborazzi tests.
Although we have the --tests parameter, it cannot filter out non-Roborazzi tests, like using --excludeTests "*ScreenshotTest."
Is there any way to achieve this? I am concerned that we should not significantly affect the standard test task.

**Comment by takahirom** [comment]
What do you think of this, feedback is welcome.

open class RoborazziExtension {
  var runOnlyRoborazziTestsWhenRoborazziTask: Boolean = false
  var roborazziTestsPattern: String = "*ScreenshotTest"
}

// plugin
        test.doFirst {
          if (roborazziExtension.runOnlyRoborazziTestsWhenRoborazziTask) {
            val isRoborazziTest = isRecordRun.get() || isVerifyRun.get() || isCompareRun.get()
            if (isRoborazziTest) {
              test.setTestNameIncludePatterns(listOf(roborazziExtension.roborazziTestsPattern))
            } else {
              test.exclude(listOf(roborazziExtension.roborazziTestsPattern))
            }
          }

**Comment by sergio-sastre** [comment]
I'm actually surprise that the --tests option does not work?

I got that [working with Paparazzi here](https://github.com/sergio-sastre/Android-screenshot-testing-playground#gradle-tests)

Let me try later in the evening...

If not, I'm not aware of a better option.
However,the naming runOnlyRoborazziTestsWhenRoborazziTask is very confusing, and having roborazzi as variable name inside a roborazzi taks is very redundant. I suggest sth like this
```
roborazzi {
  testsFilterOption = "include"// "exclude"
  testsFilterPattern = "*ScreenshotTest"
}
```

**Comment by takahirom** [comment]
The reason I added the flag is that simply adding the plugin affects the test task, which I believe is not ideal.

**Comment by takahirom** [comment]
However, if we set testsFilterOption to disable by default, it won't affect the test task. That might be a good approach 👀

**Comment by takahirom** [comment]
However, the name you suggested is a bit confusing because this flag affects both the testDebugUnitTest task and the RoborazziTasks. Let me explain with an example:

Test files:

ArticleTest
ArticleScreenshotTest
Executing tasks:

Run ./gradlew testDebugUnitTest: Executes ArticleTest
Run ./gradlew recordRoborazziDebug: Executes ArticleScreenshotTest

**Comment by sergio-sastre** [comment]
Okay, I think I misread it.

Imho, Roborazzi plugin options should ONLY affect Roborazzi tasks.

If somebody wants to exclude Roborazzi tests when running unit tests, he should do it in the gradle file (it is not supported via --tests option)
For instance, pack Roborazzi tests in a different package, and then adjust your gradle file to filter them out:

```groovy
test {
     filter {
         excludeTestsMatching "screenshottests.*"
     }
}
```
then, by running `./gradlew testDebugUnitTest`, no Roborazzi tests run

**Comment by takahirom** [comment]
The challenging aspect of this issue is that your configuration affects not only the non-Roborazzi tests, but also the Roborazzi tests themselves, which prevents us from taking screenshots.

I wish I could get a code like this to work, but I can't seem to filter it.

```
  testOptions {
    unitTests {
      includeAndroidResources = true
      all { test ->
        if (systemProperties["roborazzi.test.record"] == "true") {
          test.getFilter().setExcludePatterns "*Test*"
        }
      }
    }
  }
```

**Comment by sergio-sastre** [comment]
Sure, but you can pass a custom gradle property for it.

```groovy
def excludeRoborazziTests

testOptions {
    unitTests {
      ...
      all { 
         filter {
            if (project.hasProperty("excludeRoborazziTests"))
                excludeTestsMatching "screenshottests.*"
         }
      }
    }
 }
  ```

and then `./gradlew testDebugUnitTest -PexcludeRoborazziTests`

This only applies if you set the flag when running tests

**Comment by takahirom** [comment]
I will now close this issue. We can reopen it if anything arises.
