### ISSUE TITLE
Introduce dependency diff CI

### ISSUE THREAD

**Issue by takahirom** [takahirom/roborazzi#382]
We are migrating dependencies, but it's crucial for users to manage them themselves.
I would like to set up a dependency diff CI that reports changes in dependencies via pull request comments for all roborazzi-xxx modules.
It would be great if we could use dependency-diff-tldr.
https://github.com/careem/dependency-diff-tldr

**Comment by Dhruvnotfound** [comment]
how about using dependabot? it can
- Automatically check for outdated dependencies
- Update dependency files
- create pull request
https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide

**Comment by takahirom** [comment]
Thank for recommending solution. What I wanted is that I want to manage dependencies for users. We can update dependencies for tests and samples freely but if we update dependencies in library it could be breaking changes.

以下のように校正しました：

Thank you for recommending a solution. What I want is to manage dependencies for users. We can update dependencies for tests and samples freely, but if we update dependencies in the library, it could lead to breaking changes.

**Comment by takahirom** [comment]
Thank you for recommending a solution. What I want is to manage dependencies for users. We can update dependencies for tests and samples freely, but if we update dependencies in the library, it could lead to breaking changes.

**Comment by takahirom** [comment]
I have implemented this, and it seems to be working fine.
