### ISSUE TITLE
Background on screenshots when using composeRule instead of the capture method directly

### ISSUE THREAD

**Issue by eddnav** [takahirom/roborazzi#398]
In my code I have:

```
 @get:Rule
    val composeRule = createComposeRule()

    @Before
    fun setup() {
        LottieTask.EXECUTOR = Executor(Runnable::run)
    }

    @Test
    fun test() {
        composeRule.setContent {
             SomeComposableUsingLottie()
        }
        composeRule.onRoot().captureRoboImage("name.png")
    }
```

This works well, test don't hang due to Lottie, however, this causes my snapshots to have a background:
![snapshot](https://github.com/takahirom/roborazzi/assets/4434924/c8aea29b-6172-43fc-aeae-6bc9cf09f112)

What could be causing this?

If instead I just do:
```
    @Test
    fun test() {
        captureRoboImage("name.png) {
             SomeComposableUsingLottie()
        }
    }
```

My snapshots render as expected:
![snapshot](https://github.com/takahirom/roborazzi/assets/4434924/2fae8c9a-b729-402a-8d17-427119543ab9)

For everything except Composables that include Lottie of course because they never finish.

I noticed a related issue here: https://github.com/takahirom/roborazzi/issues/166. This user has the exact same issue and he resolved it by using my initial approach, but for me it's critical that my backgrounds are transparent.

**Comment by takahirom** [comment]
I can't say for sure, but I think the reason why you can't capture a transparent screenshot is that you are using the default activity. How about specifying RoborazziTransparentActivity when you use createComposeRule()?

**Comment by eddnav** [comment]
> I can't say for sure, but I think the reason why you can't capture a transparent screenshot is that you are using the default activity. How about specifying RoborazziTransparentActivity when you use createComposeRule()?

Yep! this did the trick. Very much appreciated. It might be a good idea to include `RoborazziTransparentActivity` somewhere in the readme though! In any case, thank you!
