### ISSUE TITLE
Screenshots are displayed weirdly after migrating to Type-Safety Compose Navigation

### ISSUE THREAD

**Issue by JackEblan** [takahirom/roborazzi#408]
Hi @takahirom, My screenshot images became like [these](https://github.com/JackEblan/Geto/tree/navigation-compose/feature/app-settings/src/test/screenshots) after migrating to Type-Safety Compose Navigation. My layouts are fine in my app.

e.g:
**BEFORE**
![AppSettingsScreenPopulated_foldable (1)](https://github.com/takahirom/roborazzi/assets/141921460/bb46e1c9-04d4-460c-afb8-97c641c7bbb2)

**AFTER**
![AppSettingsScreenPopulated_foldable](https://github.com/takahirom/roborazzi/assets/141921460/953197ab-ee47-424b-80a3-4315f0a64ae1)

**Comment by takahirom** [comment]
Thanks. Do you have a code diff? You can use the dump option of RoborazziOptions to debug.

**Comment by takahirom** [comment]
I've cloned your repository and debugging the tests 👀

**Comment by JackEblan** [comment]
I suspected, it has to do something with Navigation Compose = "2.8.0-beta03" version. It also broke some spacing to my layouts. Funny I never touched anything. I should haven't file an issue here. I'll close this now. Sorry for inconvenience ✌️

![Screenshot_20240616-161334](https://github.com/takahirom/roborazzi/assets/141921460/c0cc0b1c-b055-48b5-9694-52494415e7a0)

**Comment by takahirom** [comment]
@JackEblan I updated the Robolectric's version and it seems fixed 👀

**Comment by takahirom** [comment]
Please wait we might have to add `it.systemProperties["robolectric.pixelCopyRenderMode"] = "hardware"` as well

        testOptions {
            unitTests {
                // For Robolectric
                isIncludeAndroidResources = true

                isReturnDefaultValues = true
                all {
                    it.systemProperties["robolectric.pixelCopyRenderMode"] = "hardware"
                }
            }

**Comment by takahirom** [comment]
Sorry, I might have been mistaken. I'll take a closer look.

**Comment by takahirom** [comment]
I have submitted a pull request for this:
https://github.com/JackEblan/Geto/pull/164

I believe the issue is fixed now. Could you please review it?
For information on robolectric.pixelCopyRenderMode, you can refer to this link:
https://github.com/takahirom/roborazzi/issues/296

**Comment by takahirom** [comment]
Please wait for the screenshots to be updated.
https://github.com/takahirom/Geto/pull/1
