### ISSUE TITLE
Integrate ComposablePreviewScanner

### ISSUE THREAD

**Issue by yschimke** [takahirom/roborazzi#415]
https://github.com/sergio-sastre/ComposablePreviewScanner requires apps do the integration with the preferred screenshot library

Example https://github.com/sergio-sastre/ComposablePreviewScanner?tab=readme-ov-file#roborazzi

But it could be a great experience if the roborazzi plugin had an option to enable screenshot testing of previews with no extra code or config.

Theoretical developer Steps

1. Use previews in a gradle project
2. Add `io.github.takahirom.roborazzi` plugin to build
3. Configure via RoborazziExtension

```
roborazzi {
  automaticPreviewScreenshots = true
}
```

This would cover maybe 80% of a typical apps screenshots, while promoting routine use of Previews for development, and allowing unit tests for the other 20%.

**Comment by takahirom** [comment]
Thank you for your proposal! I think it is great to have APIs that users can set up easily, while also having basic APIs for advanced usages. For example, we can add dependencies like Robolectric and options like hardware rendering when using the automatic option.

**Comment by takahirom** [comment]
One challenge is automatically adding a test. Here's how I think we can add a test:

```kotlin
      testTaskProvider
        .configureEach { test: AbstractTestTask ->
          val resultsDir = resultDirFileProperty.get().asFile
          if(test is Test) {
            val generateTestsTaskProvider = project.tasks.register("generateTests", GenerateTestsTask::class.java) {
              it.dependsOn("generateTests")
            }
            test.testClassesDirs += project.files(generateTestsTaskProvider.map { it.outputDir })
          }

....

abstract class GeneratePreviewScreenshotTestsTask : DefaultTask() {
    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generateTests() {
        val testDir = outputDir.get().asFile
        testDir.mkdirs()

        File(testDir, "GeneratedPreviewScreenshotTest.kt").writeText("""
            import org.junit.Test

            class GeneratedPreviewScreenshotTest {
                @Test
                fun testPreviewScreenshot() {
                }
            }
        """.trimIndent())
    }
}
```

**Comment by takahirom** [comment]
I think we can implement this feature by following these steps:

1. Add the automaticPreviewScreenshots Gradle extension property.
2. Add dependencies like Robolectric and ComposablePreviewScanner if automaticPreviewScreenshots exists.
3. Add the GeneratePreviewScreenshotTestsTask and set it up if automaticPreviewScreenshots exists.

**Comment by sergio-sastre** [comment]
I think it is important to mention that ComposablePreviewScanner is based on [ClassGraph](https://github.com/classgraph/classgraph) which finds the Previews while running the jvm tests (so no code generation or ksp involved), and such tests run at [build-time as stated here](https://github.com/classgraph/classgraph/wiki/Build-Time-Scanning#gradle-code)

Theoretically it should be possible, but I am a little bit unsure how good it works inside a Gradle plugin, and I think the first step would be to try it out and see if it finds some Composables in a very basic gradle plugin that does nothing else but that.

That would be the very first step I’d try.

Regarding the mapping between the Previews and Robolecteic/Roborazzi, I can help with that once I am back from Droidcon Berlin 😊

**Comment by takahirom** [comment]
Thanks. I'm thinking of adding a generated test, which uses `ComposablePreviewScanner`, to the test Gradle task to generate screenshots instead of loading Previews in the Gradle Plugin. This approach is easier and would allow users to migrate their own customized tests. If you have any opinions on this, please let me know.

Sadly, I don't have time to implement this now, so I added the `contributions welcome` label. I'll be available in late September.

**Comment by sergio-sastre** [comment]
Oh I see, that should definitely work without troubles

**Comment by takahirom** [comment]
With just adding one hundred lines of code, it seems to have worked 🎉 
 https://github.com/takahirom/roborazzi/pull/416/files#diff-2ec7175e0bee85fe7e7d1d5d40dbf060b59731fcbd6dac9cc2db230a9ed84876R22
All users have to do is add this.

```
plugins {
  id("io.github.takahirom.roborazzi")
}

roborazzi {
  automaticPreviewScreenshots {
    enabled = true
    scanPackages = listOf("com.github.takahirom.sample")
  }
}
```

**Comment by takahirom** [comment]
I have a small issue: I'm not sure how we can access the version catalog during compile time from the plugin.

https://github.com/takahirom/roborazzi/blob/8d68dea6f3a9372d931d73451d75c3a1a5dffd17/include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/PreviewScreenshots.kt#L49-L63

**Comment by yschimke** [comment]
Is naming of multipreviews a follow up? It wasn't clear it's handled.

But amazing, ship it!

**Comment by sergio-sastre** [comment]
Wow! Super fast 🏎️
I’ll try to do a code review today in the evening (CET time)

**Comment by takahirom** [comment]
I'm thinking of changing the DSL to make it more flexible. 

**Current Configuration:**
```kotlin
roborazzi {
  automaticPreviewScreenshots {
    enabled = true
    scanPackageTrees = listOf("com.github.takahirom.sample")
  }
}
```

**Proposal:**
Minimum setup for preview screenshot tests:

```kotlin
roborazzi {
  androidSetup {
    enable = true
    generatePreviewTests {
      scanPackages = listOf("com.github.takahirom.sample")
    }
  }
}
```

You can disable or enable all setups:

```kotlin
roborazzi {
  androidSetup {
    enable = true
    generatePreviewTests {
      enable = true // Inherits from setupOptions if not specified
      scanPackages = listOf("com.github.takahirom.sample")
    }
    libraryDependencies {
      enable = true
      robolectricVersion = "1.xxx"
    }
    testConfig {
      enable = false
      includeAndroidResources = true
      roborazziFilePathStrategy = "relativeFromOutputDir"
      robolectricRenderMode = "hardware"
    }
  }
}
```

**Comment by takahirom** [comment]
These changes allow users to copy and reuse GeneratedPreview tests, disable specific settings like dependencies, and easily set up screenshot tests even if they opt not to use Preview Screenshot tests. We can also introduce new settings with defaults set to false. Additionally, naming the setup as androidSetup leaves room for possible expansion to Kotlin Multiplatform."

**Comment by takahirom** [comment]
I also think It's confusing. I'm thinking additional abstraction layer for users.

```kotlin
roborazzi {
  baseSetupConfig(
    AndroidAutomaticPreviewScreenshots(listOf("com.github.takahirom.sample"))
  )
  advancedAndroidSetup {
    libraryDependencies.junitVersion = "4.13.2"
  }
}
```

**Comment by yschimke** [comment]
I don't think you should get involved in dependencies at all. I think the pattern from Hilt, Compose and gRPC (IIRC) is to fail the build if they are unmet, with a clear error, and often a way to suppress.

So I'd suggest minimising the changes to the project structure and dependencies, instead executing the code paths you planned and explaining the requirements to the user.

**Comment by takahirom** [comment]
That's a good point. I've been considering what should and shouldn't be included in our scope. For example, I was wondering about the differences between setting dependencies and adding new tasks in the plugin. Adding tasks and properties means they become the single source of configuration, but changing something users can already configure can lead to losing that single source of truth.

I've come up with the following API. This setup checks dependencies and configurations and generates necessary source codes without altering user settings:

```kotlin
roborazzi {
  generateRobolectricPreviewTests {
      enable = true
      pacakges = listOf("com.github.takahirom.sample")
  }
}
```

**Comment by yschimke** [comment]
Looks good. Typo in packages aside.

**Comment by takahirom** [comment]
Thank you. I have re-implemented the PR based on the feedback.
https://github.com/takahirom/roborazzi/pull/416

**Comment by yschimke** [comment]
That looks great to me.  Keen to try it.

**Comment by sergio-sastre** [comment]
@takahirom 
I’ve added support for private previews in ComposablePreviewScanner 0.1.3 in case you also want to let users set that in the plugin

**Comment by takahirom** [comment]
Thank you for letting me know. We don't have versioning in our documents, and there are no errors, so I think it's fine to leave it as is.
I'll close this issue! Thank you for your review and proposal.
