### ISSUE TITLE
Wrong path in report used for images on Windows

### ISSUE THREAD

**Issue by ben-gooding-hub** [takahirom/roborazzi#417]
`..\C:\Users\Path-To-My-Project\Project-abc\snapshots\build\outputs\roborazzi\Example-exampleName_compare.png`
^^ This path is used in the HTML report

It should be without the `..\` at the start or a relative path

![image](https://github.com/takahirom/roborazzi/assets/55401790/c51afd82-e8f5-4d8e-9704-ec567eae85c7)

**Comment by takahirom** [comment]
Thank you for reporting this bug. I'll take a look.
