### ISSUE TITLE
[roborazzi-idea-plugin] has no icon when using Android Studio with new theme setting.

### ISSUE THREAD

**Issue by wezley98** [takahirom/roborazzi#420]
<img width="558" alt="Screenshot 2024-07-02 at 17 15 01" src="https://github.com/takahirom/roborazzi/assets/1488209/bd892e66-1bb5-4d32-a71e-dbcb38b91fd1">

When not selected

<img width="218" alt="Screenshot 2024-07-02 at 17 15 22" src="https://github.com/takahirom/roborazzi/assets/1488209/5ebfae17-b2f3-4ab7-8d7a-fde32ae4eacf">

**Comment by takahirom** [comment]
Thanks! I'll fix this issue

**Comment by takahirom** [comment]
This fix has been released! Thank you for reporting!
