### ISSUE TITLE
[Feature Request] Private Preview Annotation Support

### ISSUE THREAD

**Issue by yuchan2215** [takahirom/roborazzi#441]
I would like to request support for private previews.
I suggest adding an option to use `includePrivatePreviews()` when working with ComposablePreviewScanner.

Reference Links:
- [ComposablePreviewScanner's Documentation](https://github.com/sergio-sastre/ComposablePreviewScanner/blob/4d899cfe6e5243bb03f8b1381719581423de6e40/README.md?plain=1#L86)
- [Roborazzi Code](https://github.com/takahirom/roborazzi/blob/b10e3e96f8f2fbdc47c3ce632e42192aa7561fed/roborazzi-compose-preview-scanner-support/src/main/java/com/github/takahirom/roborazzi/RoborazziPreviewScannerSupport.kt#L45)

**Comment by yuchan2215** [comment]
Furthermore, defining `ComposePreviewTester` during troubleshooting can be a hassle, so it would be very convenient if i could also pass `RoborazziOptions`.

**Comment by sergio-sastre** [comment]
I think the RoborazziOptions should be discussed in a different issue.

I would not pass Roborazzi options to the plugin
but have an extra module containing the RoborazziConfig annotation with the Options. So each Preview can have its own RoborazziOptions.

So the only you’d have to do is to map the annotation arguments to RoborazziOptions in the composablePreview module.

You can find the docu and a link to an example here:
https://github.com/sergio-sastre/ComposablePreviewScanner?tab=readme-ov-file#roborazzi

**Comment by takahirom** [comment]
@yuchan2215 Thank you for bringing this to our attention. Could you create a separate issue for customizing RoborazziOptions?

**Comment by takahirom** [comment]
To support Private Preview Annotation, I added the contributions welcome label to this issue.
