### ISSUE TITLE
Compose Preview friction 

### ISSUE THREAD

**Issue by yschimke** [takahirom/roborazzi#446]
https://takahirom.github.io/roborazzi/preview-support.html#generate-compose-preview-screenshot-tests

seems incomplete, running with 1.23.0 my gradle sync fails with 

```
Please set roborazzi.generateRobolectricPreviewTests.packages in the generatePreviewTests extension or set roborazzi.generateRobolectricPreviewTests.enable = false.See https://github.com/sergio-sastre/ComposablePreviewScanner?tab=readme-ov-file#how-to-use for more information.
```

Could this fail at runtime instead?  And should it be in the docs?

**Comment by yschimke** [comment]
Also error  

```
e: file:///usr/local/google/home/yschimke/workspacesda/StudioProjects/confetti/wearApp/build/generated/java/generateDebugComposePreviewRobolectricTests/com/github/takahirom/roborazzi/RoborazziPreviewParameterizedTests.kt:8:8 Unresolved reference 'sergio'.
```

Following instructions

**Comment by takahirom** [comment]
👀

**Comment by yschimke** [comment]
I also needed 

```
                          testImplementation("io.github.takahirom.roborazzi:roborazzi-compose-preview-scanner-support:0.1.0")
```

without attempting "Manually adding Compose Preview screenshot tests﻿"

**Comment by yschimke** [comment]
Could AndroidComposePreviewTester be public (experimental) and open?

I need to run some tearDown, and it seems awkward without lifecycle hooks.

**Comment by yschimke** [comment]
Warnings on compiling

```
w: file:///usr/local/google/home/yschimke/workspacesda/StudioProjects/confetti/wearApp/build/generated/java/generateDebugComposePreviewRobolectricTests/com/github/takahirom/roborazzi/RoborazziPreviewParameterizedTests.kt:24:13 This declaration needs opt-in. Its usage should be marked with '@com.github.takahirom.roborazzi.ExperimentalRoborazziApi' or '@OptIn(com.github.takahirom.roborazzi.ExperimentalRoborazziApi::class)'
```

**Comment by takahirom** [comment]
Thank you for trying this out.
Regarding dependencies, we have some dependency validations in place [here](https://github.com/takahirom/roborazzi/blob/main/include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/GenerateComposePreviewRobolectricTestsExtension.kt#L305-L308). I expected there would be an error with the validation. 
It might be better to provide a link to the [sample](https://github.com/takahirom/roborazzi/tree/main/sample-generate-preview-tests) for a smoother setup process.

**Comment by yschimke** [comment]
If you need a specific support library from roborazzi, it feels appropriate to add that, even though we discussed not messing with the robolectric dependencies.

**Comment by takahirom** [comment]
Whether to add dependencies in the plugin or not is a tough decision, as I initially added them all. You mentioned Hilt and Compose, which don't even add their runtime dependencies in the plugin. It's difficult to decide if something is a 'specific support library'; for example, Hilt Android support also doesn't add the runtime dependency. I also find that if we have a library dependency in 'roborazzi-compose-preview-scanner-support', it can be difficult for users to exclude that library dependency.

**Comment by yschimke** [comment]
OK, makes sense.
