### ISSUE TITLE
Fix issue where task run button is cropped in IDE plugin

### ISSUE THREAD

**Issue by takahirom** [takahirom/roborazzi#454]
<img width="379" alt="image" src="https://github.com/user-attachments/assets/59414e1f-e0e4-4e3e-bd79-2c95051a0f9c">

**Comment by takahirom** [comment]
@eyedol Thanks for refactoring the layout. I noticed that the task run button is now cropped, and we need to expand the toolbar to see it. Do you know of any good ways to avoid this?

**Comment by eyedol** [comment]
It was because the JBBox was anchored to the west. See #455 for a possible fix. wdyt?
