### ISSUE TITLE
Add A11y transform

### ISSUE THREAD

**Issue by yschimke** [takahirom/roborazzi#46]
For inspiration https://github.com/joreilly/Confetti/blob/de9c9cd1f309071a44f6879c637e895770573a81/androidTest/src/main/kotlin/dev/johnoreilly/confetti/screenshot/a11y/A11ySnapshotTransformer.kt#L17

Results in screenshots like https://github.com/joreilly/Confetti/blob/de9c9cd1f309071a44f6879c637e895770573a81/wearApp/snapshot/ConferenceHomeScreenTest/conferenceHomeScreenA11y_Colors_Material__reference.png

![image](https://user-images.githubusercontent.com/231923/233776319-a54c0978-736a-44d7-a36d-eb326c8b1460.png)

**Comment by takahirom** [comment]
We have a dump feature in this library. How about customizing it for accessibility (A11y)?
https://github.com/takahirom/roborazzi#dump-mode

**Comment by takahirom** [comment]
@yschimke 
I've implemented it. Could you take a look?
https://github.com/takahirom/roborazzi/pull/55
