### ISSUE TITLE
Roborazzi iOS fails to run due to the error: "Polymorphic serializer for class com.github.takahirom.roborazzi.CaptureResult.Recorded has property 'type' that conflicts with JSON class discriminator"

### ISSUE THREAD

**Issue by takahirom** [takahirom/roborazzi#463]
## What happened

I noticed that roborazzi-compose-ios has an error, although CI is passing. However, the CI is actually being skipped. The reason for this is that GitHub has switched macos-latest to arm64, and we are running `compareRoborazziIosX64`. We may need to add `compareRoborazziIosArm64` to CI and fix the issue.
I ran git bisect and identified the first commit causing the error as 217b53d8621d0bcc80123830d5db967ae1148879.

## How to reproduce

```
./gradlew compareRoborazziIosArm64 compareRoborazziIosX64
```

**Comment by takahirom** [comment]
@eyedol Thank you, as always. Do you recall this PR?

**Comment by eyedol** [comment]
Aarrgghh. I remember that PR. I'll look into it 💪🏿
