### ISSUE TITLE
Add examples using robolectric @Config

### ISSUE THREAD

**Issue by yschimke** [takahirom/roborazzi#47]
Useful to show configuring the screen for different devices. Round vs Square watch.

These qualifiers should also affect which resources are loaded

```
@Config(
    sdk = [30],
    qualifiers = "w221dp-h221dp-small-notlong-notround-watch-xhdpi-keyshidden-nonav"
)
```

```
@Config(
    sdk = [30],
    qualifiers = "w221dp-h221dp-small-notlong-round-watch-xhdpi-keyshidden-nonav"
)
```

**Comment by yschimke** [comment]
We could provide constants for known devices, similar to Paparazzi, and Android Studio.

```
@Preview(device = Devices.NEXUS_5X)
```

And config in https://cs.android.com/android-studio/platform/tools/adt/idea/+/mirror-goog-studio-main:artwork/resources/device-art-resources/wearos_small_round/layout

https://github.com/cashapp/paparazzi/blob/c10c435bd30025f3b5da64f846c6ecbd66d54515/paparazzi/paparazzi/src/main/java/app/cash/paparazzi/DeviceConfig.kt#L475

https://android.googlesource.com/platform/tools/base/+/mirror-goog-studio-master-dev/sdklib/src/main/java/com/android/sdklib/devices/wear.xml

**Comment by sergio-sastre** [comment]
> We could provide constants for known devices, similar to Paparazzi, and Android Studio.
> 
> ```
> @Preview(device = Devices.NEXUS_5X)
> ```
> 
> And config in https://cs.android.com/android-studio/platform/tools/adt/idea/+/mirror-goog-studio-main:artwork/resources/device-art-resources/wearos_small_round/layout
> 
> https://github.com/cashapp/paparazzi/blob/c10c435bd30025f3b5da64f846c6ecbd66d54515/paparazzi/paparazzi/src/main/java/app/cash/paparazzi/DeviceConfig.kt#L475
> 
> https://android.googlesource.com/platform/tools/base/+/mirror-goog-studio-master-dev/sdklib/src/main/java/com/android/sdklib/devices/wear.xml

That is actually sth I’m releasing next week:
https://twitter.com/gio_sastre/status/1649073964617019400?s=46&t=ljy1XQW5SI3KUXpinEKEow

in this library:
https://github.com/sergio-sastre/AndroidUiTestingUtils

However, that is sth that would depend on ActivityScenario. So I believe, it might make sense to have this directly in Roborazzi?

It’s indeed very straightforward to implement.

**Comment by takahirom** [comment]
Is this what you mean? I think it would be very useful to have.

```kotlin
object RobolectricDeviceQualifiers {
  const val NEXUS_5X = "w320dp-h540dp-xxxhdpi..."
...
}
```

**Comment by yschimke** [comment]
Yep.

I don't know whether you need some data model for devices with different properties, but this is what I was asking for.

A data model might be useful for non robolectric running, or to copy and adjust. But robolectric has those APIs.

**Comment by takahirom** [comment]
If we use the annotations provided by Robolectric, they don't allow us to implement methods similar to a builder. Consequently, we have no choice but to use constants. We can also use RuntimeEnvironment.setQualifiers("+land"). However, if the test is initiated by a Rule, the activity might already be started.
https://robolectric.org/device-configuration/
Nevertheless, we sometimes wish to conduct tests with variations, such as for smartphones and tablets.
This is indeed a challenging issue, but for now, I think it's acceptable to have some constants in place.

**Comment by takahirom** [comment]
We can implement something similar to the example below. However, I believe it may not be the best solution.

```kotlin
fun test() {
...
}

@Config(
    sdk = [30],
    qualifiers = "w221dp-h221dp-small-notlong-notround-watch-xhdpi-keyshidden-nonav"
)
@Test
fun testRound() = test()
@Config(
    sdk = [30],
    qualifiers = "w221dp-h221dp-small-notlong-round-watch-xhdpi-keyshidden-nonav"
)
@Test
fun testNotRound() = test()
```

**Comment by takahirom** [comment]
I think this is useful 👀 
https://android.googlesource.com/platform/tools/base/+/mirror-goog-studio-master-dev/sdklib/src/main/java/com/android/sdklib/devices/nexus.xml#2837

**Comment by sergio-sastre** [comment]
It seems that the x and y dimensions (width and height) are in pixels, and you need them in dpi (that’s what Robolectric supports).

Moreover, only a few device characteristics are configurable via qualifiers.

**Comment by sergio-sastre** [comment]
> If we use the annotations provided by Robolectric, they don't allow us to implement methods similar to a builder. Consequently, we have no choice but to use constants. We can also use RuntimeEnvironment.setQualifiers("+land"). However, if the test is initiated by a Rule, the activity might already be started.
> https://robolectric.org/device-configuration/
> Nevertheless, we sometimes wish to conduct tests with variations, such as for smartphones and tablets.
> This is indeed a challenging issue, but for now, I think it's acceptable to have some constants in place.

That’s true, that’s why to do it dynamically, it must be linked to the ActivityScenarioTestRule.

but the solution with the constants is already a good improvement over the standard Robolectric solution imho 😊

**Comment by takahirom** [comment]
I'm nearly finished with the task. It's harder than I thought. 😅 

```kotlin
package com.github.takahirom.roborazzi

import java.io.File
import javax.xml.parsers.DocumentBuilderFactory
import org.junit.Test
import org.w3c.dom.Document
import org.w3c.dom.Node
import org.w3c.dom.NodeList

class GenerateQualifiersTest {
  @Test
  fun generate() {
    println(File(".").absolutePath)
    val xmlFiles =
      File("../scripts/devices").listFiles().toList().filter { it.name.endsWith(".xml") }
    println(xmlFiles)
    xmlFiles
      .forEach { xmlFile ->
        // parse xml
        val documentBuilderFactory = DocumentBuilderFactory.newInstance()
        val documentBuilder = documentBuilderFactory.newDocumentBuilder()
        val document: Document = documentBuilder.parse(xmlFile)

        val devices = document.getElementsByTagName("d:device").toList()

        devices.forEach { device ->
          // find device name
          val deviceNodes = device.childNodes.toList()
          val name = deviceNodes.first { it.nodeName == "d:name" }.textContent
          println(name)
          println(deviceNodes)

          val hardwareNodes = deviceNodes.first { it.nodeName == "d:hardware" }.childNodes.toList()
          println(hardwareNodes)

          val screenNodes = hardwareNodes.first { it.nodeName == "d:screen" }.childNodes.toList()
          println(screenNodes)
          val screenDimensionsNodes = screenNodes.first { it.nodeName == "d:dimensions" }.childNodes.toList()
          val xDimention = screenDimensionsNodes.first { it.nodeName == "d:x-dimension" }.textContent
          println(xDimention)

        }
      }
  }

  private fun NodeList.toList(): List<Node> {
    val list = mutableListOf<Node>()
    for (i in 0 until length) {
      list.add(item(i))
    }
    return list
  }
}
```

```kotlin
Nexus 5
[[#text: 
        ], [d:name: null], [#text: 
        ], [d:id: null], [#text: 
        ], [d:manufacturer: null], [#text: 
        ], [d:playstore-enabled: null], [#text: 
        ], [d:hardware: null], [#text: 
        ], [d:software: null], [#text: 
        ], [d:state: null], [#text: 
        ], [d:state: null], [#text: 
    ]]
[[#text: 
            ], [d:screen: null], [#text: 
            ], [d:networking: null], [#text: 
            ], [d:sensors: null], [#text: 
            ], [d:mic: null], [#text: 
            ], [d:camera: null], [#text: 
            ], [d:camera: null], [#text: 
            ], [d:keyboard: null], [#text: 
            ], [d:nav: null], [#text: 
            ], [d:ram: null], [#text: 
            ], [d:buttons: null], [#text: 
            ], [d:internal-storage: null], [#text: 
            ], [d:removable-storage: null], [#text: 
            ], [d:cpu: null], [#text: 
            ], [d:gpu: null], [#text: 
            ], [d:abi: null], [#text: 
            ], [d:dock: null], [#text: 
            ], [d:power-type: null], [#text: 
            ], [d:skin: null], [#text: 
        ]]
[[#text: 
                ], [d:screen-size: null], [#text: 
                ], [d:diagonal-length: null], [#text: 
                ], [d:pixel-density: null], [#text: 
                ], [d:screen-ratio: null], [#text: 
                ], [d:dimensions: null], [#text: 
                ], [d:xdpi: null], [#text: 
                ], [d:ydpi: null], [#text: 
                ], [d:touch: null], [#text: 
            ]]
1080
```

**Comment by takahirom** [comment]
I have implemented the feature. Please let me know if there's anything wrong with what I've done.
https://github.com/takahirom/roborazzi/pull/49

**Comment by yschimke** [comment]
I suspect these are the configs we want for Wear, and probably other devices. Sorry for the bad link before.  I can put up a PR.

https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:sdklib/src/main/resources/com/android/sdklib/devices/

Wear OS Large Round
Wear OS Small Round
Wear OS Rectangular
Wear OS Square

Instead of the current

```
  const val WearOSSquare = "w187dp-h187dp-small-long-round-watch-hdpi-keyshidden-nonav"
  const val WearOSRound = "w213dp-h213dp-small-long-round-watch-hdpi-keyshidden-nonav"
  const val WearOSRoundChin = "w240dp-h218dp-small-notlong-notround-watch-tvdpi-keyshidden-nonav"
```
