### ISSUE TITLE
Capturing toasts and popups

### ISSUE THREAD

**Issue by ArcaNO93** [takahirom/roborazzi#474]
Hello there!

I wonder whether it is possible to capture toasts and compose popups via Roborazzi?

Capturing dialogs works fine.

Thanks

**Comment by takahirom** [comment]
For composing dialogs, you can use the captureScreenRoboImage method. Could you check it out? I think we can't check toasts, but we can verify them using Robolectric features.

**Comment by ArcaNO93** [comment]
dialogs work just fine
what im interested in is toast\compose popup

**Comment by takahirom** [comment]
This is a test that uses `captureScreenRoboImage()`. I'm not sure if the dropdown menu is a popup. If you could provide sample code, that would be great.
https://github.com/DroidKaigi/conference-app-2024/pull/816#issuecomment-2310251421

**Comment by ArcaNO93** [comment]
i guess its not a popup so it will be visible on snapshots without problems
i cant really provide a code due to NDA, but it would be a simple `Toast.makeTest().show()` and then capturing it via `captureScreenRoboImage`

**Comment by ArcaNO93** [comment]
and it didnt work for me 
so i wonder whether its possible to capture dialogs only

**Comment by takahirom** [comment]
I think ShadowToast changes the behavior, and if we could somehow remove the ShadowToast, it might work. However, I always use ShadowToast.getTextOfLatestToast() to check the toast.

**Comment by takahirom** [comment]
Sorry, the implementation of Toast uses NotificationManager. I think we can't show the toast even if we disable ShadowToast. It is a major trade-off of Robolectric, as launching another activity is not supported, so we can't use it for now.
