### ISSUE TITLE
Filtering Images by Text Field in IntelliJ Plugin

### ISSUE THREAD

**Issue by takahirom** [takahirom/roborazzi#475]
When we use parameterized tests or something like https://github.com/takahirom/robospec, it is difficult to find the image we want to see. If we have a text field to filter images by file name, I think it would be very convenient to use.

You can debug the IntelliJ Plugin by running `./gradlew runIde`

https://github.com/takahirom/roborazzi/blob/main/roborazzi-idea-plugin/src/main/kotlin/com/github/takahirom/roborazzi/idea/preview/RoborazziPreviewTool.kt

**Comment by sanao1006** [comment]
I'd like to try this task!
I haven't started anything yet, but I might be able to get by with `JBTextField`.

**Comment by takahirom** [comment]
@sanao1006 Sounds good! I would love to use this feature.
