### ISSUE TITLE
[IDE Plugin] Display Message for Unavailable Roborazzi Task Selection in IntelliJ Plugin

### ISSUE THREAD

**Issue by yuchan2215** [takahirom/roborazzi#493]
# Overview
The UI shown in the image is not displayed.
<img width="360" alt="image" src="https://github.com/user-attachments/assets/f4a83164-9865-40d0-b088-c80b758e3c21">

# Workaround
Please check the following setting:
`Configure all Gradle tasks during Gradle Sync (this can make Gradle Sync slower)`
<img width="553" alt="image" src="https://github.com/user-attachments/assets/e4773385-953a-419b-a0db-a8ea5559fb67">
Next, execute an appropriate task.

# Other
I am not very good at English, so I am using ChatGPT.

**Comment by takahirom** [comment]
Oh, I didn't know this. I think this setting is necessary to show Gradle tasks. It would be beneficial to provide this explanation to users, something like: "To enable the display of Roborazzi tasks, please enable 'Configure all Gradle tasks during Gradle Sync (this can make Gradle Sync slower)' in the settings."

**Comment by takahirom** [comment]
You can run the Roborazzi IntelliJ Plugin by using `./gradlew runIde` if you want to contribute.

**Comment by sanao1006** [comment]
@takahirom 
hi!
As a solution to this issue, I thought of adding the following text to the Roborazzi settings window: Note: "To enable the display of Roborazzi tasks, please enable 'Configure all Gradle tasks during Gradle Sync (this can make Gradle Sync slower)' in the settings." What do you think? 
The position where the text should be placed is roughly as shown in the image.
Also, perhaps adding a similar explanation to the README might be effective.
![image](https://github.com/user-attachments/assets/e11c37be-ea4d-411a-8963-16505f8af7a7)

**Comment by takahirom** [comment]
@sanao1006 That sounds great. 👍  We will definitely check the screen when we can't find the tasks.
