### ISSUE TITLE
Feature request: provide PNG of actual result when verifying

### ISSUE THREAD

**Issue by alexjlockwood** [takahirom/roborazzi#50]
For example, when verifying it seems like there are two things that end up in the `build/outputs/roborazzi` directory:

- The original image that was recorded in a previous "record" step 
- A comparison image that compares the recorded image above with the new/actual image

It would be nice if the "new/actual" image could also be provided separately. This way we can easily use it as a new baseline recorded image if we wish (i.e. if the changes in the test are actually intentional and we want to update our "golden value" image to use the next time the test is run).

**Comment by takahirom** [comment]
Thanks. I would like to clarify your request. The new image will be saved as "{file_name}_actual.png". Is this what you are looking for?

**Comment by takahirom** [comment]
If you don't mind, can you take a look at this PR? https://github.com/takahirom/roborazzi/pull/51
