### ISSUE TITLE
Roborazzi IntelliJ plugin can't find my screenshots

### ISSUE THREAD

**Issue by timothyfroehlich** [takahirom/roborazzi#502]
Hey! I'm finally trying out the new plugin, but I've not had any luck in getting it to work properly.

So I have our roborazzi rule set up to record images to "src/testDebug/roborazzi", with the class name of the test appended. So for example, `integration-tests/validation/src/testDebug/kotlin/com/android/designcompose/testapp/validation/InteractionTests.kt` records screenshots to `integration-tests/validation/src/testDebug/roborazzi/InteractionTests`. But I've tried setting the images directory path to both `src/testDebug/roborazzi` and `src/testDebug/roborazzi/InteractionTests` but either way the Preview window still says "Nothing to show". It's definitely detecting the module correctly, but I've got no luck seeing the screenshots. Can't find anything interesting in intelliJ's logs either.

How can I help figure this out?

![image](https://github.com/user-attachments/assets/2af3dfd7-ad75-43a3-8571-2cd43d1e71db)

**Comment by takahirom** [comment]
Thank you. I'm working on this.

**Comment by timothyfroehlich** [comment]
Just tried it, the update works great!
