### ISSUE TITLE
The minimum requirements are unclear

### ISSUE THREAD

**Issue by jmatsu** [takahirom/roborazzi#53]
It would be great if the following requirements are also noted in README to introduce this plugin to several projects. 

- Android Gradle Plugin version
- Gradle version
- JRE version

I found the min version of Robolectric (it's 4.10 alpha or later) by the way.

**Comment by takahirom** [comment]
Thank you for raising this issue. Including these points can indeed be beneficial for users. However, there are some considerations to keep in mind:

* The maintenance cost and potential risk of outdated documentation.
* The fact that some libraries (e.g., Dropshots, Paparazzi, and facebook/screenshot-tests-for-android) don't include these sections.

Considering these factors, it might be a good approach to address compatibility requirements if and when someone encounters a problem. This way, you can balance the benefits of providing information with the need to keep documentation up to date and relevant.

As for your question, have you experienced any issues with those versions? Knowing this will help us determine the best course of action.

**Comment by jmatsu** [comment]
I understood the approach. 

> As for your question, have you experienced any issues with those versions? Knowing this will help us determine the best course of action.

I haven't faced any problem yet. I will open a new issue if I have a trouble. Thanks in advance.
