### ISSUE TITLE
Webp comparing issues

### ISSUE THREAD

**Issue by ArcaNO93** [takahirom/roborazzi#546]
hey @takahirom 
1st of all, thank you for this webp feature, it seems to be working very nice (at least the recording part xD)
as for comparing, i've got some weird issues
like
<img width="232" alt="Screenshot 2024-11-08 at 09 21 41" src="https://github.com/user-attachments/assets/64c26e25-2ab0-4492-8972-9eeceae3372c">
most of them are related to gradients we use

what may cause this? is there a need to adapt comparing algorythm for webps?
thanks

**Comment by ArcaNO93** [comment]
thats image comparator
    public open val imageComparator: SimpleImageComparator = SimpleImageComparator(maxDistance = 0.0f, hShift = 1)

and results validator
    public open val resultValidator: (ImageComparator.ComparisonResult) -> Boolean by lazy {
        ThresholdValidator(threshold = maxDiff.toFloat())
    }

**Comment by ArcaNO93** [comment]
just found out that PixelConfig.Rgb565 does not work with webp recording

java.io.IOException: Incompatible image: BufferedImage@6e7bd96c: type = 8 DirectColorModel: rmask=f800 gmask=7e0 bmask=1f amask=0 ShortInterleavedRaster: width = 550 height = 60 #numDataElements 1

**Comment by takahirom** [comment]
@ArcaNO93 
Thank you for reporting this issue. We have a test that checks the WebP comparison, but it may not be sufficient.
Could you share a composable function or view that we can use to reproduce the problem?

**Comment by ArcaNO93** [comment]
unfortunately cant say much cause of NDA
but
all of failing tests are connected with gradients and custom canvases
for example
here we have three layers with different offsets and color filter
```
    Canvas(modifier = modifier) {
        scaleImage(scaleX = X) {
            drawImage(
                image = image1,
                topLeft = offset1,
                colorFilter = filter1
            )
        }
        scaleImage(scaleX =  X) {
            drawImage(
                image = image2,
                topLeft = offset2,
                colorFilter = filter2
            )
        }
        scaleImage(scaleX = X) {
            drawImage(
                image = image3,
                topLeft = offset3,
                colorFilter = filter3
            )
        }
    }
    ```
    
    does it help?

**Comment by takahirom** [comment]
I was able to reproduce the problem. However, I was unable to figure out what the difference is.

It seems that GitHub doesn't support WebP, so I saved this image as a PNG.
![com github takahirom roborazzi sample boxed LosslessWebpTest whenCompareSameImageWithGradientsTheCompareImageShouldNotBeGenerated_compare copy 2](https://github.com/user-attachments/assets/819fa965-a4ab-4589-8cb1-e7cf8f7f0202)


```kotlin
  @Test
  fun whenCompareSameImageWithGradientsTheCompareImageShouldNotBeGenerated() {
    boxedEnvironment {
      ROBORAZZI_DEBUG = true
      provideRoborazziContext().setImageExtension("webp")
      val prefix =
        DEFAULT_ROBORAZZI_OUTPUT_DIR_PATH + "/" + DefaultFileNameGenerator.generateFilePath().nameWithoutExtension
      val expectedOutput =
        File("$prefix.webp")
      val expectedCompareOutput = File("${prefix}_compare.webp")
      expectedOutput.delete()
      expectedCompareOutput.delete()
      try {
        val canvasUi = @Composable {
          // Show Canvas transparent gradient
          Canvas(modifier = Modifier.fillMaxSize()) {
            drawRect(
              color = Color(0xFF000000),
              topLeft = Offset(0f, 0f),
              size = Size(100f, 100f)
            )
            drawRect(
              brush = Brush.verticalGradient(
                colors = listOf(Color(0xFF000000), Color(0x00000000)),
                startY = 0f,
                endY = 100f
              ),
              topLeft = Offset(100f, 0f),
              size = Size(100f, 100f)
            )
            // Color patterns
            drawRect(
              brush = Brush.horizontalGradient(
                colors = listOf(Color(0xFFFF0000), Color(0x00000000)),
                startX = 0f,
                endX = 100f
              ),
              topLeft = Offset(0f, 100f),
              size = Size(100f, 100f)
            )
            drawRect(
              brush = Brush.linearGradient(
                colors = listOf(Color(0xFF00FF00), Color(0x00000000)),
                start = Offset(100f, 100f),
                end = Offset(200f, 200f)
              ),
              topLeft = Offset(100f, 100f),
              size = Size(100f, 100f)
            )
            drawRect(
              brush = Brush.radialGradient(
                colors = listOf(Color(0xFF0000FF), Color(0x00000000)),
                center = Offset(150f, 150f),
                radius = 50f
              ),
              topLeft = Offset(100f, 100f),
              size = Size(100f, 100f)
            )
          }
        }
        captureRoboImage(
          filePath = expectedOutput.absolutePath,
          roborazziOptions = RoborazziOptions(
            taskType = RoborazziTaskType.Record,
            recordOptions = recordOptions
          )
        ) {
          canvasUi()
        }
        DefaultFileNameGenerator.reset()
        captureRoboImage(
          filePath = expectedOutput.absolutePath,
          roborazziOptions = RoborazziOptions(
            taskType = RoborazziTaskType.Compare,
            recordOptions = recordOptions
          ),
        ) {
          canvasUi()
        }
        assert(expectedOutput.exists())
        assert(!expectedCompareOutput.exists())
      } finally {
//        expectedCompareOutput.delete()
      }
    }
  }
```

**Comment by takahirom** [comment]
I might be able to fix this. 😅 The image difference caused by WebP has been resolved.
<img width="873" alt="image" src="https://github.com/user-attachments/assets/a9affaea-bc1d-407d-889c-43bf4d7d78ee">

**Comment by ArcaNO93** [comment]
good stuff
thanks!

**Comment by takahirom** [comment]
However, the image suggests that the red color changes from the middle, indicating that WebP images do not consistently return a red value of r = 1 for transparent colors. I couldn't identify the cause of this issue.

**Comment by ArcaNO93** [comment]
we ll its better than it was :-)
