### ISSUE TITLE
Build Errors if ComposePreviewScanner Version is in Version Catalog.

### ISSUE THREAD

**Issue by ivanisidrowu** [takahirom/roborazzi#549]
Hi, I'm trying to use the ComposePreviewScanner Version with `libs.versions.toml` file as the following code...
```
[libraries]
composable-preview-scanner = { group = "com.github.sergio-sastre.ComposablePreviewScanner", name = "android", version.ref = "composable-preview-scanner" }
```
It blocked the build with errors of the build extension.
https://github.com/takahirom/roborazzi/blob/7e37f910619e1700b31e9f211aba55e57df8ff69/include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/GenerateComposePreviewRobolectricTestsExtension.kt#L304

If I don't use catalog in the kts file, the build will passed.
```
testImplementation("io.github.sergio-sastre.ComposablePreviewScanner:android:0.3.2")
```
Would it be possible to avoid this check for catalog? Thanks in advance.

**Comment by takahirom** [comment]
@ivanisidrowu 
Thanks. I think the group name should be `Compos**able**PreviewScanner` instead of `Compos**e**PreviewScanner`. If there are any other questions, please let me know.

**Comment by takahirom** [comment]
Does it happen even if you use `Compos**able**PreviewScanner`?

**Comment by ivanisidrowu** [comment]
Sorry, I don't understand `Compos**able**PreviewScanner`. Could you elaborate more about this?

Or are you suggesting to make changes like this?
```
[libraries]
composable-preview-scanner = { group = "com.github.sergio-sastre.Compos**able**PreviewScanner", name = "android", version.ref = "composable-preview-scanner" }
```
I used the catalog in roborazzi 1.24.0, it worked. However, it's not working in the latest version.

**Comment by ivanisidrowu** [comment]
Ah, I see now. The package name was changed. I tried it, and it worked. Thank you! This lib is cool 😎
