### ISSUE TITLE
All the test pass but it failed because of serialization `overrides final method error`

### ISSUE THREAD

**Issue by williamtan1989** [takahirom/roborazzi#556]
```
> Failed to notify test listener.
   > class kotlinx.serialization.json.internal.AbstractJsonTreeDecoder overrides final method kotlinx.serialization.internal.TaggedDecoder.decodeInline(Lkotlinx/serialization/descriptors/SerialDescriptor;)Lkotlinx/serialization/encoding/Decoder;
```

I have absolutely no idea why I received that error, it was working before v1.16.0, but once I bumped the library version up to v1.16.0+.. I started getting that error.. which i suspect was due to `Gson to Kotlinx.serialization migration` in v1.16.0..

Any idea how can I solve this?

**Comment by takahirom** [comment]
Thanks. I think this might be a version issue with Kotlinx Serialization. The library versions for the superclass and subclass might be different. Could you check it out?

**Comment by takahirom** [comment]
I took a brief look. 👀 
I believe `AbstractJsonTreeDecoder` is part of `kotlinx-serialization-json`, and its superclass belongs to `kotlinx-serialization-core-jvm`. However, I'm not sure why your build dependencies are using an older version.

We are using KotlinX Serialization JSON 1.6.3.  
https://github.com/takahirom/roborazzi/blob/main/include-build/roborazzi-gradle-plugin/build.gradle#L21C19-L21C48  
https://github.com/takahirom/roborazzi/blob/main/gradle/libs.versions.toml  

KotlinX Serialization changed the method to non-final in version `[1.5.1](https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.5.1)`.  
https://github.com/Kotlin/kotlinx.serialization/commit/fc9aef532349fa910394c03b1cc741a4ef575712  

KotlinX Serialization JSON 1.6.3 depends on `kotlinx-serialization-core-jvm`.  
https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-serialization-json-jvm/1.6.3  

Therefore, I think, in a normal environment, `kotlinx-serialization-core-jvm` 1.6.3 should be used.

**Comment by williamtan1989** [comment]
Interesting.. I don't even have `kotlinx-serialization-core-jvm` library in my dependencies.. maybe it's from other libraries.. let me run `./gradlew dependencies` to check and get back to you! Thank you!

**Comment by takahirom** [comment]
You might need to use `./gradlew buildEnvironment` to display the `buildScript` dependencies. 🙏

**Comment by williamtan1989** [comment]
I tried `./gradlew buildEnvironment` which actually looks from the output.. there's no problem with roborazzi dependency, in fact it's the only library that have serialization-json dependency..

However, from `./gradlew dependencies`, I found out that in `io.gitlab.arturbosch.detekt:1.23.5`.. one of the transitive library, `io.gitlab.arturbosch.detekt:detekt-report-sarif` have `kotlinx-serialization-json:1.4.1` as dependency 🫠 .. 

So, since this is not an issue with roborazzi, I'll close this issue! Thank you very much!
