### ISSUE TITLE
roborazzi.cleanupOldScreenshots=true issue with custom paths

### ISSUE THREAD

**Issue by pacoalface-jt** [takahirom/roborazzi#580]
Hi!
After adding the `roborazzi.cleanupOldScreenshots=true` property, I noticed that the library is not removing the old screenshots (I've tried renaming a screenshot test to check the funcionality), I'm using a custom path for the screenshots folder and I suspect this could be the problem. I've cloned the library project and everything worked fine using the default path, but changing it to a custom one it's not removing the images. An easy way to replicate it would be by renaming a test [here](https://github.com/takahirom/roborazzi/blob/6c75d3ac225a38c456ec17bd7bb580d185401788/sample-android/src/test/java/com/github/takahirom/roborazzi/sample/RuleTestWithPath.kt) 

Thanks!

**Comment by pacoalface-jt** [comment]
Hi!
We are setting the roborazzi.outputDir through a common Roborazzi rule, something like:

```
RoborazziRule(
    options = RoborazziRule.Options(
        outputDirectoryPath = "./screenshots",
        outputFileProvider = { description, outputDirectory, fileExtension ->
            File(
                outputDirectory,
                "${description.testClass.name}_${description.methodName}.$fileExtension",
            )
        },
    ),
)
```

We're doing in this way because we have a lot of modules and we want to have different screenshot folders for each module, and it's easy to forget to add it on each gradle file.

I've tried to add it on one of the modules we have in the build.gradle file, but it looks like it's inmutable

**Comment by pacoalface-jt** [comment]
Thanks for your answer, setting it in that way works perfectly 🙌

**Comment by takahirom** [comment]
@pacoalface-jt 
Changing the outputDir might cause a problem because the option changes the directory for comparison images. I solved this issue in version 1.36.0. Could you try using version 1.36.0?
https://github.com/takahirom/roborazzi/releases/tag/1.36.0

**Comment by pacoalface-jt** [comment]
@takahirom of course, thanks for sharing the issue 🙏

**Comment by eboudrant** [comment]
> Thanks. We can't know which directory your tests will use, so it is necessary. You might have to use `roborazzi { outputDir.set("your folder") }` in Groovy or Kotlin. 🙇
> 
> [roborazzi/include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt](https://github.com/takahirom/roborazzi/blob/21d5de0b5df42b5e390d816cfbd64a51b5031e30/include-build/roborazzi-gradle-plugin/src/integrationTest/java/io/github/takahirom/roborazzi/RoborazziGradleProject.kt#L313)
> 
> Line 313 in [21d5de0](/takahirom/roborazzi/commit/21d5de0b5df42b5e390d816cfbd64a51b5031e30)
> 
>                outputDir.set(file("$customOutputDirPath"))

@takahirom looks like `cleanupOldScreenshots` isn't working when you use `outputFileProvider` from the test rule and use sub directories? We use a provide so we can create directories where we store the screenshots from the test package/class names. Ex:

```kotlin
outputFileProvider = { description, outputDirectory, fileExtension ->
    File(
        outputDirectory,
        "${description.testClass.name.replace('.' , File.separatorChar)}${File.separatorChar}${description.methodName}.$fileExtension",
    )
},
```

**Comment by takahirom** [comment]
@eboudrant 
Thank you for letting me know. Are you specifying `roborazzi.outputDir` in Gradle? I checked the implementation, and we are using `walkTopDown`, which means the files should be removed if they are in the directory. 
https://github.com/takahirom/roborazzi/blob/401a37344961342c58eae614937fe53c84a4e3b6/include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt#L176C27-L176C38

**Comment by eboudrant** [comment]
Actually I'm just using `recordRoborazziDebug` with  the`roborazzi.cleanupOldScreenshots=true` option set. Looking at the [code](https://github.com/takahirom/roborazzi/blob/401a37344961342c58eae614937fe53c84a4e3b6/include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt#L633) it doesn't seem to look at sub-dirs in the output dir for cleanup.

But thank for the link you shared, looks like I can just run the 2 tasks:
```
./gradlew clearRoborazziDebug recordRoborazziDebug
```

PS: Would be cool to have a similar task to paparazzi: `cleanRecordPaparazziDebug`

**Comment by takahirom** [comment]
Thanks for looking into this. It does seem like a bug.
I've created an issue for it here: https://github.com/takahirom/roborazzi/issues/684

The `cleanRecordPaparazziDebug` task sounds like an interesting idea. I can see why that would be useful. Thanks for suggesting it.

**Comment by eboudrant** [comment]
Thanks, great support!
