### ISSUE TITLE
"Could not read path" sporadic error

### ISSUE THREAD

**Issue by edenman** [takahirom/roborazzi#587]
Seeing this sporadically.  Re-running usually works but it's pretty annoying.  The command I'm running
```./gradlew :my:module:recordRoborazzi```
Error:
```
* What went wrong:
Execution failed for task ':my:module:finalizeTestRoborazziDebug'.
> Could not read path '/Users/edenman/workspace/repo/my/module/build/test-results/roborazzi/results/203200044202666_com.package.MyScreenshotTest.testName[theme=DIM].json'.
```
roborazzi 1.17.0
gradle 8.9
agp 8.2.2

**Comment by takahirom** [comment]
Thank you for reporting this. Could you try recording with recordRoborazziDebug? I think you are running the tasks in parallel. We might need to have each flavor to avoid this.

**Comment by takahirom** [comment]
If it is difficult to avoid using the specified valiant, I would like to know. I'm not sure if there are good use cases where we intentionally run multiple valiants for tests.

**Comment by edenman** [comment]
haven't seen this since switching to recordRoborazziDebug, thanks!

**Comment by takahirom** [comment]
Thanks. I think it is difficult to solve because most users don't need to have build variant folders. At least, if we could have a warning for this issue, it would be great. However, getting tasks to run could be challenging. 💭
