### ISSUE TITLE
All compose screenshots now have transparent background

### ISSUE THREAD

**Issue by pedromfmachado** [takahirom/roborazzi#598]
Hey there 👋

In one of the latest releases, [1.35.0](https://github.com/takahirom/roborazzi/compare/1.34.0...1.35.0#) to be precise, the introduction of [this line](https://github.com/takahirom/roborazzi/compare/1.34.0...1.35.0#diff-ca48d8eb457e701480caac0b27ef2ec5c72ead6598e6970df5e9dc519d666d84R8) seems to override the application theme.

```diff
+    setTheme(android.R.style.Theme_Translucent_NoTitleBar_Fullscreen)
```

This makes most of our tests fail because they're now transparent instead of following the colors defined by the theme applied in our application class. I've created a workaround to manually apply the desired theme to all our Roborazzi screenshot tests, but would definitely like to move on to a more robust solution.

Is this intended behaviour? I'd be glad to contribute with a fix if you have any idea how to better deal with it! 🙂

**Comment by takahirom** [comment]
@pedromfmachado 
Thank you for reporting this. I think we should have mentioned this in the release notes. The new `RoborazziComposeOptions` might be helpful. Could you try using the `background` option in `RoborazziComposeOptions`?

```kotlin
@OptIn(ExperimentalRoborazziApi::class)
@Test
fun captureComposeLambdaImage() {
    captureRoboImage(
        roborazziComposeOptions = RoborazziComposeOptions {
            background(
                showBackground = true
            )
        }
    ) {
        Text("Hello Compose!")
    }
}
```

**Comment by takahirom** [comment]
I've added this to the release notes.  
https://github.com/takahirom/roborazzi/releases/tag/1.35.0

**Comment by pedromfmachado** [comment]
Just FYI and if someone is facing the same problem, we decided to resort to:
```kotlin
composeRule.setContent(composable)
composeRule.onRoot().captureRoboImage(file = getFile(name))
```
rather than `composeRule { composable() }`  as this allows for the flexibility of using our own activity and theme.

**Comment by takahirom** [comment]
I think it would be good to provide a `RoborazziComposeActivityThemeOption`. Do you have time to add this?

**Comment by pedromfmachado** [comment]
I'll find some time to create a PR soon, sure!

**Comment by mattinger** [comment]
@takahirom  I'm assuming this should probably be made part of the rule? 

We are having a somewhat related problem in that when we use this type of test after upgrading AGP to 8.7.3:

```
runComposeTest { 
   setContent {
      ...
   }
   onRoot().captureRoboImage()
}
```

We're now getting the built in action bar on ComponentActivity, and for some reason that is overlayed over our content.
I found a simple workaround is to create an AndroidManifest.xml in your `src/test` folder set the theme on application object.

```
<application android:theme="@style/Theme.AppCompat.Light.NoActionBar" />
```

Another option is to change the activity altogether by using the  `runAndroidComposeUiTest` function which lets you specify which activity you want to use (`runComposeTest` sets that to `ComponentActivity`)

**Comment by takahirom** [comment]
I have filed the issue.
https://issuetracker.google.com/issues/383368165

**Comment by takahirom** [comment]
I'm considering adding this kind of workaround to Roborazzi.

https://github.com/takahirom/roborazzi/blob/0f7ad42d937629850258d9a56749a6cb9884d172/include-build/roborazzi-core/src/androidMain/kotlin/com/github/takahirom/roborazzi/ViewScreenshot.kt#L116
<img width="720" alt="image" src="https://github.com/user-attachments/assets/01da7f84-67e8-4410-a321-97a48d0cdb66">

**Comment by takahirom** [comment]
I think it is necessary to use window rendering to display shadows. However, I'm not sure about Compose and the current situation.

**Comment by takahirom** [comment]
I think this workaround doesn't work because the View is a window here, and the window has the action bar.

**Comment by takahirom** [comment]
I think we can show warning or something at least.

**Comment by takahirom** [comment]
Thank you for providing alternatives.

I'm considering adding this workaround. However, using the view's draw method doesn't capture the background, resulting in a transparent background. Despite this, it might be a better experience than having the action bar overlap issue.
@mattinger Could you take a look this code?
https://github.com/takahirom/roborazzi/pull/604

**Comment by sergio-sastre** [comment]
What if you add the proposed theme

```xml
<application android:theme="@style/Theme.AppCompat.Light.NoActionBar" />
```
to the theme of the RoborazziTransparentActivity?

Or there is a problem with the manifest merging?

**Comment by sergio-sastre** [comment]
Or alternatively in `RoborazziTransparentActivity`:

```kotlin

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Request features before setting the content view
    Window windowToUse = getWindow();
    windowToUse.requestFeature(Window.FEATURE_NO_TITLE);

    setContentView(R.layout.activity_main);
}

```

**Comment by takahirom** [comment]
Thanks. I think it is better to have results similar to Android Studio's Composable Preview. In Composable Preview, if there is no background, the preview does not include a background. Therefore, I think it would be better to have a transparent color as the default.
<img width="520" alt="image" src="https://github.com/user-attachments/assets/ddb4e9ae-fb4b-441a-bc64-4595c2b1f94a" />

**Comment by sergio-sastre** [comment]
> Thanks. I think it is better to have results similar to Android Studio's Composable Preview. In Composable Preview, if there is no background, the preview does not include a background. Therefore, I think it would be better to have a transparent color as the default. <img alt="image" width="520" src="https://private-user-images.githubusercontent.com/1386930/395480858-ddb4e9ae-fb4b-441a-bc64-4595c2b1f94a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwODAxMTcsIm5iZiI6MTczNDA3OTgxNywicGF0aCI6Ii8xMzg2OTMwLzM5NTQ4MDg1OC1kZGI0ZTlhZS1mYjRiLTQ0MWEtYmM2NC00NTk1YzJiMWY5NGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTNUMDg1MDE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTVjNWY4MWY0OGIxODBlMjc3NTU2YjA5NzBmN2Y4OWQwMmJkZDJiZGVmMTFmMzdmMjM5ZGUwMDdlYjFjZDJhYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.m6Wk9v9cDUSLUPbkNHpBN5xOIRmED6aRxuaLLABxQhw">

I agree… However, I’m skeptical about implementing a workaround that does not fully work because you have to give up on some other functionality (i.e. shadows)

better to experiment a bit and see how we could make it work properly

**Comment by pedromfmachado** [comment]
I will take some time today to make a PR with a proposal on how this could be addressed, let's use it as a baseline for the discussion. 🙂

**Comment by takahirom** [comment]
>I agree… However, I’m skeptical about implementing a workaround that does not fully work because you have to give up on some other functionality (i.e. shadows)
better to experiment a bit and see how we could make it work properly.
there are several options to try here… like allowing to pass a custom Activity or using ContextWrapper to apply a theme and likely some others that are worth trying

@sergio-sastre 
Thanks. I tried to see if the shadow rendering is appropriate. And I can't find the area we need to fix. Could you elaborate on where we need to improve?

<img width="1203" alt="image" src="https://github.com/user-attachments/assets/c3e5abef-8edd-4358-9860-59a51e35c21f" />

**Comment by sergio-sastre** [comment]
> Thank you for providing alternatives.
> 
> I'm considering adding this workaround. However, using the view's draw method doesn't capture the background, resulting in a transparent background. Despite this, it might be a better experience than having the action bar overlap issue. @mattinger Could you take a look this code? #604

I meant the workaround in this PR. I have currently no computer where I can check it though, but I see on my phone that the new screenshot has no shadow?

**Comment by takahirom** [comment]
Ah, I see what you mean. I have a reason for using this approach, but I’ll think about it a bit more and get back to you tomorrow.

**Comment by takahirom** [comment]
@pedromfmachado I apologize for the confusion. I believe the RoborazziComposeActivityThemeOption is still necessary for `captureRoboImage{}` use cases. This is distinct from the `composeRule.onRoot().captureRoboImage()` use cases we discussed previously, which have already been addressed.

**Comment by pedromfmachado** [comment]
Hey @takahirom, thanks for clarifying, I was not on-par with the discussion yet. 🙂 I was not able to do it so far, but will create a PR in the next couple of days.
