### ISSUE TITLE
Compose 1.7 Some icons rendering incorrectly

### ISSUE THREAD

**Issue by mattinger** [takahirom/roborazzi#602]
I'm having some issues with certain icons rendering properly in snapshot tests.  Here's my environment:

Gradle: 8.9
AGP: 8.7.3
Kotlin: 2.0.21
Robolectric: 4.14.1
Robolectric SDK: 34
Roborazzi: 1.36.0
Compose BOM: 2024.11.00
Material3: 1.3.1

This only happens when recording snapshots, and not when i deploy to an emulator or device.  But some icons just don't render properly.  Here's the code which produces the snapshot:

```
@RunWith(AndroidJUnit4::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
class ExampleUnitTest {
    @get:Rule
    val roborazziRule = RoborazziRule(
        options = RoborazziRule.Options(
            roborazziOptions = RoborazziOptions(
                compareOptions = RoborazziOptions.CompareOptions(
                    changeThreshold = 0.001F
                )
            )
        )
    )


    @OptIn(ExperimentalTestApi::class)
    @Test
    fun iconIssue() {
        runComposeUiTest {
            setContent {
                Icon(
                    painter = painterResource(R.drawable.cl_ic_bluetooth_outline),
                    contentDescription = null
                )
            }
            onRoot().captureRoboImage()
        }
    }
}
```

Here is the resulting snapshot, where you can clearly see that it's filling in the triangles in the bluetooth icon that should be empty, as well as producing other areas of the icon with content that shouldn't be there.

![com xfinity dh iconsnapshotissue ExampleUnitTest iconIssue](https://github.com/user-attachments/assets/d4d634bf-7c50-49fc-81e0-7b655195b053)

Along with the source xml drawable:

[cl_ic_bluetooth_outline.xml.tgz](https://github.com/user-attachments/files/18099594/cl_ic_bluetooth_outline.xml.tgz)

This seems to have started when we upgraded to Compose 1.7 from 1.6.

**Comment by takahirom** [comment]
I don't think there's much we can do within Roborazzi to fix this vector drawable issue. I recommend creating an issue in Robolectric, as the problem might be related to Robolectric, Compose, and the Android runtime.

**Comment by mattinger** [comment]
FYI:  https://github.com/robolectric/robolectric/issues/9887

**Comment by takahirom** [comment]
Thanks. I'll close this issue.
