### ISSUE TITLE
DefaultFileNameGenerator should be configurable

### ISSUE THREAD

**Issue by yschimke** [takahirom/roborazzi#66]
It would be nice to be able to set some alternative strategy instead of DefaultFileNameGenerator

Particularly when transitioning from another test library.

**Comment by takahirom** [comment]
The issue is how we should integrate the generator. Should it be a static field or part of the test runner?

**Comment by takahirom** [comment]
Using a static value can be problematic because it may break other tests. However, users can create a Test Rule to revert it to the default value after the test is completed.

**Comment by yschimke** [comment]
I'd suggest part of the config, but hopefully also including the directory structure.

**Comment by takahirom** [comment]
@yschimke 
Would adding RoborazziOptions work for you? Something like this: 👀

```
fun View.captureRoboImage(
  roborazziOptions: RoborazziOptions = RoborazziOptions(),
  filePath: String = roborazziOptions.recordOptions.generator,
)
```

**Comment by yschimke** [comment]
An option would help.

I don't quite follow

```
filePath: String = roborazziOptions.recordOptions.defaultFileNameGenerator()
```

What is the String value returned, or is it `(...) -> String`?

**Comment by takahirom** [comment]
How about providing `defaultFileNameGenerator : () -> String` parameter and RunningTestFinder class?

```kotlin
object RunningTestFinder {
  fun findMethod(): Method? {
    // Find test method name
    val allStackTraces = Thread.getAllStackTraces()
    ...
    ...
  }
}
```

**Comment by yschimke** [comment]
> How about providing `defaultFileNameGenerator : () -> String` parameter and RunningTestFinder class?
> 
> ```kotlin
> object RunningTestFinder {
>   fun findMethod(): Method? {
>     // Find test method name
>     val allStackTraces = Thread.getAllStackTraces()
>     ...
>     ...
>   }
> }
> ```

Anything with a `Rule` already knows it's a test and gets `org.junit.runner.Description`, so should be able to do this without walking the stacktrace.

I'm not sure if you support roborazzi outside of unit tests, but maybe the Rule can implement this in a way with `(Description) -> File`?

**Comment by yschimke** [comment]
apologies for being vague. It's not a critical requirement, I can just move my screenshot files around.

**Comment by takahirom** [comment]
> apologies for being vague. It's not a critical requirement, I can just move my screenshot files around.

I understand your concerns, and they are reasonable. So, it's okay.

If we don't use JUnit rules, we cannot use Description. That's why DefaultFileNameGenerator is there.

**Comment by takahirom** [comment]
@yschimke 
I just realized that DefaultFileNameGenerator has two public functions and it takes Description when you use JUnit Rule. So, I think we can pass the Description as a parameter for the provider function. Can you take a look at this?
https://github.com/takahirom/roborazzi/pull/74
