### ISSUE TITLE
White background on component images

### ISSUE THREAD

**Issue by yschimke** [takahirom/roborazzi#67]
Existing screenshots before roborazzi 

<img width="488" alt="image" src="https://user-images.githubusercontent.com/231923/235940566-278f3d40-3fb7-4348-a305-0c6404b80e31.png">

After roborazzi https://github.com/google/horologist/pull/1234

<img width="486" alt="image" src="https://user-images.githubusercontent.com/231923/235940864-809792a3-ec30-4d9f-8e58-0d155725d4db.png">

**Comment by takahirom** [comment]
How did you take this capture? Did you perhaps use this method? Maybe we should use a transparent Activity theme 👀 
https://github.com/takahirom/roborazzi/blob/main/roborazzi/src/main/java/com/github/takahirom/roborazzi/Roborazzi.kt#L187

**Comment by yschimke** [comment]
Test is here https://github.com/google/horologist/blob/61d33dfd081c37d83fe063a46f73d06b9e6ea88e/base-ui/src/test/java/com/google/android/horologist/base/ui/components/PrimaryChipTest.kt

```
@RunWith(AndroidJUnit4::class)
@GraphicsMode(GraphicsMode.Mode.NATIVE)
@Config(
    sdk = [30],
    qualifiers = RobolectricDeviceQualifiers.WearOSLargeRound
)
class PrimaryChipTest {
    @get:Rule
    val composeTestRule = createAndroidComposeRule<ComponentActivity>()

    @get:Rule
    val roborazziRule = RoborazziRule(
        composeRule = composeTestRule,
        captureRoot = composeTestRule.onRoot(),
        options = RoborazziRule.Options(
            captureType = RoborazziRule.CaptureType.LastImage,
            outputDirectoryPath = "src/test/snapshots/images",
            roborazziOptions = RoborazziOptions(
                recordOptions = RoborazziOptions.RecordOptions(
                    pixelBitConfig = RoborazziOptions.PixelBitConfig.Rgb565
                )
            )
        )
    )
```

I've just realised I'm not setting a Theme, on Wear, it should default to black.  Which would be better, but I'd prefer transparent.

Just realised it might be because I'm not using ARGB_8888

**Comment by yschimke** [comment]
Still happening with ARGB_8888

**Comment by takahirom** [comment]
@yschimke 
I fixed the transparency issue in the Compose lambda. Could you take a look at it?
https://github.com/takahirom/roborazzi/pull/70/files#diff-803f492ee7fd2febd9bf50f3ecb157e7d2fb40d2b2cd6faa36a6be33e4b119a1R189
