### ISSUE TITLE
--rerun-tasks Required for Saving Baseline Using Cache

### ISSUE THREAD

**Issue by galisamas** [takahirom/roborazzi#97]
Hey, 

I am trying to run Roborazzi snapshots in the pipeline which is configured on Jenkins. However, I am facing a few issues (or maybe this is something I misunderstood in the setup process and you will be able to guide me). There are two issues that I want to stress, which might be related:

Prerequisites: 
- I am running the `1.2.0` version
- Have baseline stored in the project
- I am using the most simple Roborazzi Rule setup. `RoborazziRule(onView(isRoot()))`

1. Running verifyRoborazziDebug task in Jenkins.
No matter what `path` I will declare in the `captureRoboImage(path)` for the snapshot using, it will always fail. However, this doesn't apply to the local gradle task run. I have a test that should be using a custom `path` to record and verify the snapshot state. It works locally, but in Jenkins, I always get this:
```
<...>MyTest > example1 FAILED
    java.lang.AssertionError: Roborazzi: /var/lib/jenkins/workspace/<...>/build/outputs/roborazzi/example1_compare.png is added.
    See compare image at /var/lib/jenkins/workspace/<...>/build/outputs/roborazzi/example1_compare.png
        at com.github.takahirom.roborazzi.RoborazziOptions$RoborazziCompareReporter$VerifyRoborazziCompareReporter.report(capture.kt:349)
        at com.github.takahirom.roborazzi.RoborazziKt.processOutputImageAndReport(Roborazzi.kt:666)
        at com.github.takahirom.roborazzi.RoborazziKt.saveLastImage(Roborazzi.kt:472)
        at com.github.takahirom.roborazzi.RoborazziKt.access$saveLastImage(Roborazzi.kt:1)
        at com.github.takahirom.roborazzi.RoborazziKt$captureAndroidView$3.invoke(Roborazzi.kt:432)
        at com.github.takahirom.roborazzi.RoborazziKt$captureAndroidView$3.invoke(Roborazzi.kt:431)
        at com.github.takahirom.roborazzi.RoborazziRule$apply$1.evaluate(RoborazziRule.kt:133)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:589)
        at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$2(SandboxTestRunner.java:290)
        at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:99)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
It wasn't working by setting `outputDirectoryPath` too. By the stacktrace it is clear that Roborazzi is using the `DEFAULT_ROBORAZZI_OUTPUT_DIR_PATH` for the snapshot verification. 

A bit more context:
I have tried to force the snapshot to fail (with an outdated baseline) I got the `*_compare.png` generated in the `path` I declared in the `captureRoboImage(path)` method. So the outcome was as expected but logs were stating a different path to the `*_capture.png` image. When I update the baseline for the test to succeed, it had no `*_compare.png` image under the declared `path`. However, it still got me the top error.

2. Running any Roborazzi task in Jenkins.
It doesn't work properly, since it always gets the `Skipped` even tho each time I change the test count or snapshotted view content or test steps/content. As I was investigating why that happens I made a conclusion, that if Gradle consistently marks tasks as up-to-date even though they aren't, it suggests that the tasks' inputs or outputs may not be configured correctly. Roborazzi needs to ensure that any files tasks rely on are properly declared as inputs, and any files or directories tasks generate are declared as outputs. 

The only way to run the task is by adding the flag to the gradle command `./gradlew verifyRoborazzi --rerun-tasks`.

It might be related to the first issue.
```
Skipping task ':testDebugUnitTest' as it is up-to-date.
Resolve mutations for :verifyRoborazziDebug (Thread[included builds,5,main]) started.
:verifyRoborazziDebug (Thread[included builds,5,main]) started.

> Task :verifyRoborazziDebug UP-TO-DATE
Skipping task ':verifyRoborazziDebug' as it has no actions.
```

p.s. if you will try to set up a Jenkins pipeline to test, don't forget to append to the start of the `path` variable the working directory path `System.getProperty("user.dir")`. This cost me some time to figure this out.

Thanks for the great library and for the support!

**Comment by takahirom** [comment]
Thank you for reaching out with your issues. I have a couple of suggestions that may help resolve your problems:

1. If you're using `captureRoboImage()`, there's no need to declare `RoborazziRule`. Could you try removing `RoborazziRule` and see if the problem persists?

2. The error message suggests that the file `/var/lib/jenkins/workspace/<...>/build/outputs/roborazzi/example1_compare.png` is being added. Could you please verify if the file `/var/lib/jenkins/workspace/<...>/build/outputs/roborazzi/example1.png` actually exists in your Jenkins workspace?

I hope these suggestions help. Please let me know if the issues continue. I'm here to help.

**Comment by galisamas** [comment]
Thanks for the quick answer!

Removing `RoborazziRule` solved the first issue. As you mentioned, it seems that rule was adding an additional layer of capturing. So `/var/lib/jenkins/workspace/<...>/build/outputs/roborazzi/example1_compare.png` is not an issue anymore.

However, the task is still always skipped without the `--rerun-tasks` flag.

**Comment by takahirom** [comment]
Thanks, I have updated the issue title. 👍 
How about both restoring baseline images and restoring the cache? That way, we might be able to skip the task.

**Comment by galisamas** [comment]
Played with both, but was no success.

**Comment by takahirom** [comment]
@galisamas 
I would like to ask a few questions to better understand the issue.
1. **Expected Behavior**: Could you please describe what you anticipated would happen? 
2. **Actual Outcome**: What was the actual result? Please provide any error messages or logs if possible.
3. **Procedure**: Could you explain the process in more detail? For instance, when you encountered the skipped task, had the test or source code been changed? (This will help me determine whether the task being skipped is normal behavior.)

These questions will give me a clearer picture of your situation and assist in troubleshooting your issue.

**Comment by galisamas** [comment]
1. I have a recorded baseline in the project scope. Running the `verifyRoborazziDebug` task should revalidate the snapshots. Especially when any of the tests or testing code changes. So I would expect the `verifyRoborazziDebug` task to run and e.g. fail after the test is changed that snapshot would look differently. 
2. No matter what is changed in the tests or testing code scope, the `verifyRoborazziDebug` task is always marked as skipped (see initial message's 2nd code snippet).
3.  I try to change one of the screens by commenting on half of its visible views. With the correct baseline, I am running the `verifyRoborazziDebug` task in the Jenkins pipeline. Everything passes, since the `: verifyRoborazziDebug` is skipped due to no actions.

**Comment by takahirom** [comment]
Thank you. I understand the issue you're experiencing. I attempted to replicate it, but was unable to reproduce the skipped test task. Could you possibly provide any steps to reproduce the problem?  

```
 ./gradlew app:verifyRoborazziDebug  --info
# change some tests
 ./gradlew app:verifyRoborazziDebug  --info
```

And If this issue occurs only in your Jenkins environment, could you please try running testDebugUnitTest to check if the task gets skipped and whether it's a problem related to Roborazzi?

**Comment by galisamas** [comment]
Sorry for not getting back to you sooner, was off. I have a stage in the current pipeline structure that probably affects it. It builds the app and runs all tests. So when the other stage with the roborazzi or `testDebugUnitTest` is run, nothing is changed in the code and it skips the task. Briefly, `testDebugUnitTest` is skipped as well. So these might be the steps to reproduce it `./gradlew clean build check`

**Comment by takahirom** [comment]
@galisamas 
I have created some failing tests and fixed them. Can you verify if this was your intention?
<img width="580" alt="image" src="https://github.com/takahirom/roborazzi/assets/1386930/4fcb9e9a-1e24-4960-a65b-568006235c7b">

**Comment by galisamas** [comment]
Yes, it was 🙇 Thanks for your great support!
