### ISSUE TITLE
Gradle optimization failure

### ISSUE THREAD

**Issue by takahirom** [takahirom/roborazzi#98]
> Additional action of task ':lazycolumnscreen:crosslibrary:testDebugUnitTest' was implemented by the Java lambda 'io.github.takahirom.roborazzi.RoborazziPlugin$apply$1$testTaskProvider$1$Lambda$2276/0x000000080268ba78'. Reason: Using Java lambdas is not supported as task inputs. Please refer to https://docs.gradle.org/7.5/userguide/validation_problems.html#implementation_unknown for more details about this problem.

**Comment by takahirom** [comment]
I would like to do this after https://github.com/takahirom/roborazzi/pull/87 👀

**Comment by takahirom** [comment]
It seems like it may be fixed.
If you find this warning message please let me know

**Comment by blundell** [comment]
I found this warning in my build using `1.5.0-rc-1`

**Comment by takahirom** [comment]
Sorry, The code has been changed since 1.5.0-rc1.
https://github.com/takahirom/roborazzi/blob/1.5.0-rc-1/include-build/roborazzi-gradle-plugin/src/main/java/io/github/takahirom/roborazzi/RoborazziPlugin.kt#L84

**Comment by blundell** [comment]
yeah here you go: https://github.com/blundell/MvvmPractice/tree/roborazzi-repro

<img width="1437" alt="image" src="https://github.com/takahirom/roborazzi/assets/655860/d9e4702b-f5b2-4187-a458-88e74cab0279">

I just added the plugin:

https://github.com/blundell/MvvmPractice/blob/roborazzi-repro/app/build.gradle#L4

and ran the command: `./gradlew testDebugUnitTest`

**Comment by takahirom** [comment]
@blundell 
Thanks! I was able to reproduce it!
It seems that the problem is related to using Java lambdas as task inputs in Gradle 7.5, which is not supported. 

The solution to this issue is to update the Gradle version in your project. You can do this by modifying the `gradle-wrapper.properties` file to use Gradle 7.6.2. Here's the specific change:

```diff
-distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-bin.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.2-bin.zip
```

After making this change and re-running the `testDebugUnitTest` task, the warning should no longer appear. Please feel free to reach out if you have any additional questions or concerns.

**Comment by takahirom** [comment]
I'm closing this issue as the solution has been identified and shared earlier. If anyone is unable to upgrade to Gradle 7.6.2 or has other related concerns, please don't hesitate to reach out or open a new issue. Thank you!
